"""
Airport Code Lookup Utility
Provides city and country information for IATA airport codes
"""

# Comprehensive airport code database
# Format: 'CODE': ('City', 'Country')
AIRPORT_DATABASE = {
    'AAA': ('Anaa', 'French Polynesia'),
    'AAB': ('Arrabury', 'Australia'),
    'AAC': ('El Arish', 'Egypt'),
    'AAD': ('Adado', 'Somalia'),
    'AAE': ('Algiers', 'Algeria'),
    'AAF': ('Apalachicola', 'United States'),
    'AAG': ('Sao Paulo', 'Brazil'),
    'AAH': ('Aachen', 'Germany'),
    'AAI': ('Arraias', 'Brazil'),
    'AAJ': ('Cayana', 'Suriname'),
    'AAK': ('Aranuka', 'Kiribati'),
    'AAL': ('Aalborg', 'Denmark'),
    'AAM': ('Mala Mala', 'South Africa'),
    'AAN': ('Al Ain', 'United Arab Emirates'),
    'AAO': ('Anaco', 'Venezuela'),
    'AAP': ('Jakarta', 'Indonesia'),
    'AAQ': ('Anapa', 'Russia'),
    'AAR': ('Aarhus', 'Denmark'),
    'AAS': ('Jayapura', 'Indonesia'),
    'AAT': ('Altay', 'China'),
    'AAU': ('Asau', 'Samoa'),
    'AAV': ('Allan Valley', 'Philippines'),
    'AAW': ('Abbottabad', 'Pakistan'),
    'AAX': ('Araxa', 'Brazil'),
    'AAY': ('Al Ghaydah', 'Yemen'),
    'AAZ': ('Quetzaltenango', 'Guatemala'),
    'ABA': ('Abakan', 'Russia'),
    'ABB': ('Asaba', 'Nigeria'),
    'ABC': ('Los Llanos', 'Spain'),
    'ABD': ('Abadan', 'Iran'),
    'ABE': ('Allentown', 'United States'),
    'ABF': ('Abaiang', 'Kiribati'),
    'ABH': ('Alpha', 'Australia'),
    'ABI': ('Abilene', 'United States'),
    'ABJ': ('Abidjan', 'Ivory Coast'),
    'ABK': ('Kabri Dar', 'Ethiopia'),
    'ABL': ('Ambler', 'United States'),
    'ABM': ('Bamaga', 'Australia'),
    'ABN': ('Albina', 'Suriname'),
    'ABO': ('Aboisso', 'Ivory Coast'),
    'ABP': ('Atkamba', 'Papua New Guinea'),
    'ABQ': ('Albuquerque', 'United States'),
    'ABR': ('Aberdeen', 'United States'),
    'ABS': ('Abu Simbel', 'Egypt'),
    'ABT': ('Al-Baha', 'Saudi Arabia'),
    'ABU': ('Atambua', 'Indonesia'),
    'ABV': ('Abuja', 'Nigeria'),
    'ABW': ('Abau', 'Papua New Guinea'),
    'ABX': ('Albury', 'Australia'),
    'ABY': ('Albany', 'United States'),
    'ABZ': ('Aberdeen', 'United Kingdom'),
    'ACA': ('Acapulco', 'Mexico'),
    'ACB': ('Antrim County', 'United States'),
    'ACC': ('Accra', 'Ghana'),
    'ACD': ('Acandi', 'Colombia'),
    'ACE': ('Lanzarote', 'Spain'),
    'ACH': ('Altenrhein', 'Switzerland'),
    'ACI': ('Alderney', 'United Kingdom'),
    'ACJ': ('Anuradhapura', 'Sri Lanka'),
    'ACK': ('Nantucket', 'United States'),
    'ACL': ('Aguaclara', 'Colombia'),
    'ACM': ('Arica', 'Colombia'),
    'ACN': ('Ciudad Acuna', 'Mexico'),
    'ACO': ('Ascona', 'Switzerland'),
    'ACP': ('Sahand', 'Iran'),
    'ACR': ('Araracuara', 'Colombia'),
    'ACS': ('Achinsk', 'Russia'),
    'ACT': ('Waco', 'United States'),
    'ACU': ('Achutupo', 'Panama'),
    'ACV': ('Arcata', 'United States'),
    'ACX': ('Xingyi', 'China'),
    'ACY': ('Atlantic City', 'United States'),
    'ACZ': ('Zabol', 'Iran'),
    'ADA': ('Adana', 'Turkey'),
    'ADB': ('Izmir', 'Turkey'),
    'ADC': ('Andakombe', 'Papua New Guinea'),
    'ADD': ('Addis Ababa', 'Ethiopia'),
    'ADE': ('Aden', 'Yemen'),
    'ADF': ('Adiyaman', 'Turkey'),
    'ADG': ('Lenawee County', 'United States'),
    'ADH': ('Aldan', 'Russia'),
    'ADI': ('Arandis', 'Namibia'),
    'ADJ': ('Amman', 'Jordan'),
    'ADK': ('Adak Island', 'United States'),
    'ADL': ('Adelaide', 'Australia'),
    'ADM': ('Ardmore', 'United States'),
    'ADN': ('Andes', 'Colombia'),
    'ADO': ('Andamooka', 'Australia'),
    'ADP': ('Anuradhapura', 'Sri Lanka'),
    'ADQ': ('Kodiak', 'United States'),
    'ADR': ('Andrews', 'United States'),
    'ADS': ('Addison', 'United States'),
    'ADT': ('Ada', 'United States'),
    'ADU': ('Ardabil', 'Iran'),
    'ADV': ('Andover', 'United Kingdom'),
    'ADW': ('Andrews AFB', 'United States'),
    'ADX': ('Leuchars', 'United Kingdom'),
    'ADY': ('Alldays', 'South Africa'),
    'ADZ': ('San Andres Island', 'Colombia'),
    'AEA': ('Abemama', 'Kiribati'),
    'AEB': ('Baise', 'China'),
    'AED': ('Aleneva', 'United States'),
    'AEG': ('Aek Godang', 'Indonesia'),
    'AEH': ('Abeche', 'Chad'),
    'AEI': ('Algeciras', 'Spain'),
    'AEK': ('Aseki', 'Papua New Guinea'),
    'AEL': ('Albert Lea', 'United States'),
    'AEM': ('Allakaket', 'United States'),
    'AEN': ('Alenquer', 'Brazil'),
    'AEO': ('Aioun el Atrouss', 'Mauritania'),
    'AEP': ('Buenos Aires', 'Argentina'),
    'AEQ': ('Armidale', 'Australia'),
    'AER': ('Sochi', 'Russia'),
    'AES': ('Alesund', 'Norway'),
    'AET': ('Allakaket', 'United States'),
    'AEU': ('Abu Musa Island', 'Iran'),
    'AEX': ('Alexandria', 'United States'),
    'AEY': ('Akureyri', 'Iceland'),
    'AFA': ('San Rafael', 'Argentina'),
    'AFD': ('Port Alfred', 'South Africa'),
    'AFI': ('Apia', 'Samoa'),
    'AFL': ('Alta Floresta', 'Brazil'),
    'AFN': ('Jaffrey', 'United States'),
    'AFO': ('Afore', 'Papua New Guinea'),
    'AFP': ('Angers', 'France'),
    'AFR': ('Afore', 'Papua New Guinea'),
    'AFS': ('Zarafshan', 'Uzbekistan'),
    'AFT': ('Afutara', 'Solomon Islands'),
    'AFW': ('Fort Worth', 'United States'),
    'AFY': ('Afyon', 'Turkey'),
    'AFZ': ('Sabzevar', 'Iran'),
    'AGA': ('Agadir', 'Morocco'),
    'AGB': ('Augsburg', 'Germany'),
    'AGC': ('Allegheny County', 'United States'),
    'AGD': ('Anggi', 'Indonesia'),
    'AGE': ('Wangerooge', 'Germany'),
    'AGF': ('Agen', 'France'),
    'AGG': ('Angoram', 'Papua New Guinea'),
    'AGH': ('Angelholm', 'Sweden'),
    'AGI': ('Wageningen', 'Suriname'),
    'AGJ': ('Aguni', 'Japan'),
    'AGK': ('Kagua', 'Papua New Guinea'),
    'AGL': ('Wanigela', 'Papua New Guinea'),
    'AGM': ('Tasiilaq', 'Greenland'),
    'AGN': ('Angoon', 'United States'),
    'AGO': ('Magnolia', 'United States'),
    'AGP': ('Malaga', 'Spain'),
    'AGQ': ('Agrinion', 'Greece'),
    'AGR': ('Agra', 'India'),
    'AGS': ('Augusta', 'United States'),
    'AGT': ('Ciudad del Este', 'Paraguay'),
    'AGU': ('Aguascalientes', 'Mexico'),
    'AGV': ('Acarigua', 'Venezuela'),
    'AGW': ('Agnew', 'Australia'),
    'AGX': ('Agatti Island', 'India'),
    'AGY': ('Argyle', 'Australia'),
    'AGZ': ('Aggeneys', 'South Africa'),
    'AHB': ('Abha', 'Saudi Arabia'),
    'AHC': ('Amedee AAF', 'United States'),
    'AHE': ('Ahe', 'French Polynesia'),
    'AHH': ('Amery', 'United States'),
    'AHI': ('Amahai', 'Indonesia'),
    'AHN': ('Athens', 'United States'),
    'AHO': ('Alghero', 'Italy'),
    'AHS': ('Ahuas', 'Honduras'),
    'AHT': ('Amchitka', 'United States'),
    'AHU': ('Al Hoceima', 'Morocco'),
    'AIA': ('Alliance', 'United States'),
    'AIB': ('Anita Bay', 'United States'),
    'AIC': ('Aiome', 'Papua New Guinea'),
    'AID': ('Anderson', 'United States'),
    'AIE': ('Ailinglaplap', 'Marshall Islands'),
    'AIF': ('Assis', 'Brazil'),
    'AIG': ('Yalinga', 'Central African Republic'),
    'AIH': ('Aiambak', 'Papua New Guinea'),
    'AII': ('Ali-Sabieh', 'Djibouti'),
    'AIK': ('Aiken', 'United States'),
    'AIL': ('Ailigandi', 'Panama'),
    'AIM': ('Ailuk Island', 'Marshall Islands'),
    'AIN': ('Wainwright', 'United States'),
    'AIO': ('Atlantic', 'United States'),
    'AIP': ('Ailinglaplap', 'Marshall Islands'),
    'AIR': ('Aripuana', 'Brazil'),
    'AIS': ('Arorae Island', 'Kiribati'),
    'AIT': ('Aitutaki', 'Cook Islands'),
    'AIU': ('Atiu Island', 'Cook Islands'),
    'AIV': ('Aliceville', 'United States'),
    'AIY': ('Atlantic City', 'United States'),
    'AIZ': ('Lake of the Ozarks', 'United States'),
    'AJA': ('Ajaccio', 'France'),
    'AJF': ('Al-Jawf', 'Saudi Arabia'),
    'AJI': ('Agri', 'Turkey'),
    'AJJ': ('Akjoujt', 'Mauritania'),
    'AJL': ('Aizawl', 'India'),
    'AJN': ('Anjouan', 'Comoros'),
    'AJR': ('Arvidsjaur', 'Sweden'),
    'AJS': ('Abreojos', 'Mexico'),
    'AJU': ('Aracaju', 'Brazil'),
    'AJY': ('Agades', 'Niger'),
    'AKA': ('Ankang', 'China'),
    'AKB': ('Atka', 'United States'),
    'AKC': ('Akron', 'United States'),
    'AKD': ('Akola', 'India'),
    'AKE': ('Akieni', 'Gabon'),
    'AKF': ('Kufrah', 'Libya'),
    'AKG': ('Anguganak', 'Papua New Guinea'),
    'AKH': ('Prince Sultan AB', 'Saudi Arabia'),
    'AKI': ('Akiak', 'United States'),
    'AKJ': ('Asahikawa', 'Japan'),
    'AKK': ('Akhiok', 'United States'),
    'AKL': ('Auckland', 'New Zealand'),
    'AKM': ('Zakouma', 'Chad'),
    'AKN': ('King Salmon', 'United States'),
    'AKO': ('Akron', 'United States'),
    'AKP': ('Anaktuvuk Pass', 'United States'),
    'AKQ': ('Astrakhan', 'Russia'),
    'AKR': ('Akure', 'Nigeria'),
    'AKS': ('Auki', 'Solomon Islands'),
    'AKT': ('Akrotiri', 'Cyprus'),
    'AKU': ('Aksu', 'China'),
    'AKV': ('Akulivik', 'Canada'),
    'AKW': ('Aghajari', 'Iran'),
    'AKX': ('Aktobe', 'Kazakhstan'),
    'AKY': ('Sittwe', 'Myanmar'),
    'ALA': ('Almaty', 'Kazakhstan'),
    'ALB': ('Albany', 'United States'),
    'ALC': ('Alicante', 'Spain'),
    'ALD': ('Alerta', 'Peru'),
    'ALE': ('Alpine', 'United States'),
    'ALF': ('Alta', 'Norway'),
    'ALG': ('Algiers', 'Algeria'),
    'ALH': ('Albany', 'Australia'),
    'ALI': ('Alice', 'United States'),
    'ALJ': ('Alexander Bay', 'South Africa'),
    'ALK': ('Asela', 'Ethiopia'),
    'ALL': ('Albenga', 'Italy'),
    'ALM': ('Alamogordo', 'United States'),
    'ALN': ('Alton', 'United States'),
    'ALO': ('Waterloo', 'United States'),
    'ALP': ('Aleppo', 'Syria'),
    'ALQ': ('Alegrete', 'Brazil'),
    'ALR': ('Alexandra', 'New Zealand'),
    'ALS': ('Alamosa', 'United States'),
    'ALT': ('Alenquer', 'Brazil'),
    'ALU': ('Alula', 'Somalia'),
    'ALV': ('Andorra la Vella', 'Andorra'),
    'ALW': ('Walla Walla', 'United States'),
    'ALX': ('Alexander City', 'United States'),
    'ALY': ('Alexandria', 'Egypt'),
    'ALZ': ('Alitak', 'United States'),
    'AMA': ('Amarillo', 'United States'),
    'AMB': ('Ambilobe', 'Madagascar'),
    'AMC': ('Am Timan', 'Chad'),
    'AMD': ('Ahmedabad', 'India'),
    'AME': ('Alto Molocue', 'Mozambique'),
    'AMF': ('Ama', 'Papua New Guinea'),
    'AMG': ('Amboin', 'Papua New Guinea'),
    'AMH': ('Arba Minch', 'Ethiopia'),
    'AMI': ('Mataram', 'Indonesia'),
    'AMJ': ('Almenara', 'Brazil'),
    'AMK': ('Animas', 'United States'),
    'AML': ('Puerto Armuellas', 'Panama'),
    'AMM': ('Amman', 'Jordan'),
    'AMN': ('Alma', 'United States'),
    'AMO': ('Mao', 'Chad'),
    'AMP': ('Ampanihy', 'Madagascar'),
    'AMQ': ('Pattimura', 'Indonesia'),
    'AMR': ('Arno', 'Marshall Islands'),
    'AMS': ('Amsterdam', 'Netherlands'),
    'AMT': ('Amata', 'Australia'),
    'AMU': ('Amanab', 'Papua New Guinea'),
    'AMV': ('Amderma', 'Russia'),
    'AMW': ('Ames', 'United States'),
    'AMX': ('Ammaroo', 'Australia'),
    'AMY': ('Ambatomainty', 'Madagascar'),
    'AMZ': ('Ardmore', 'New Zealand'),
    'ANA': ('Anaheim', 'United States'),
    'ANB': ('Anniston', 'United States'),
    'ANC': ('Anchorage', 'United States'),
    'AND': ('Anderson', 'United States'),
    'ANE': ('Angers', 'France'),
    'ANF': ('Antofagasta', 'Chile'),
    'ANG': ('Angouleme', 'France'),
    'ANH': ('Aniwa', 'Vanuatu'),
    'ANI': ('Aniak', 'United States'),
    'ANJ': ('Zanaga', 'Congo'),
    'ANK': ('Ankara', 'Turkey'),
    'ANL': ('Andulo', 'Angola'),
    'ANM': ('Antalaha', 'Madagascar'),
    'ANN': ('Annaba', 'Algeria'),
    'ANO': ('Angoche', 'Mozambique'),
    'ANP': ('Annapolis', 'United States'),
    'ANQ': ('Tri-State', 'United States'),
    'ANR': ('Antwerp', 'Belgium'),
    'ANS': ('Andahuaylas', 'Peru'),
    'ANT': ('Antigua', 'Guatemala'),
    'ANU': ('Antigua', 'Antigua and Barbuda'),
    'ANV': ('Anvik', 'United States'),
    'ANW': ('Ainsworth', 'United States'),
    'ANX': ('Andenes', 'Norway'),
    'ANY': ('Anthony', 'United States'),
    'ANZ': ('Angus Downs', 'Australia'),
    'AOA': ('Aroa', 'Papua New Guinea'),
    'AOB': ('Annanberg', 'Papua New Guinea'),
    'AOC': ('Altenburg', 'Germany'),
    'AOD': ('Abou Deia', 'Chad'),
    'AOE': ('Anadolu', 'Turkey'),
    'AOG': ('Anshan', 'China'),
    'AOH': ('Allen County', 'United States'),
    'AOI': ('Ancona', 'Italy'),
    'AOJ': ('Aomori', 'Japan'),
    'AOK': ('Karpathos', 'Greece'),
    'AOL': ('Paso de los Libres', 'Argentina'),
    'AOM': ('Armidale', 'Australia'),
    'AON': ('Arona', 'Papua New Guinea'),
    'AOO': ('Altoona', 'United States'),
    'AOR': ('Alor Setar', 'Malaysia'),
    'AOS': ('Amook', 'United States'),
    'AOT': ('Aosta', 'Italy'),
    'AOU': ('Attopeu', 'Laos'),
    'AOV': ('Andorra', 'Spain'),
    'AOW': ('Aowa', 'Papua New Guinea'),
    'AOX': ('Aoraki', 'New Zealand'),
    'APA': ('Centennial', 'United States'),
    'APB': ('Apolo', 'Bolivia'),
    'APC': ('Napa', 'United States'),
    'APD': ('Alitak', 'United States'),
    'APE': ('San Juan Aposento', 'Peru'),
    'APF': ('Naples', 'United States'),
    'APG': ('Aberdeen', 'United States'),
    'APH': ('Camp A.P. Hill', 'United States'),
    'API': ('Apiay', 'Colombia'),
    'APJ': ('Freehold', 'United States'),
    'APK': ('Apataki', 'French Polynesia'),
    'APL': ('Nampula', 'Mozambique'),
    'APM': ('Arapongas', 'Brazil'),
    'APN': ('Alpena', 'United States'),
    'APO': ('Apartado', 'Colombia'),
    'APP': ('Asapa', 'Papua New Guinea'),
    'APQ': ('Arapiraca', 'Brazil'),
    'APR': ('April River', 'Papua New Guinea'),
    'APS': ('Anapolis', 'Brazil'),
    'APT': ('Jasper', 'United States'),
    'APU': ('Apucarana', 'Brazil'),
    'APV': ('Apple Valley', 'United States'),
    'APW': ('Apia', 'Samoa'),
    'APX': ('Arapongas', 'Brazil'),
    'APY': ('Alto Parnaiba', 'Brazil'),
    'APZ': ('Zapala', 'Argentina'),
    'AQA': ('Araraquara', 'Brazil'),
    'AQB': ('Quiche', 'Guatemala'),
    'AQG': ('Anqing', 'China'),
    'AQI': ('Qaisumah', 'Saudi Arabia'),
    'AQJ': ('Aqaba', 'Jordan'),
    'AQM': ('Ariquemes', 'Brazil'),
    'AQP': ('Arequipa', 'Peru'),
    'AQS': ('Saqani', 'Fiji'),
    'AQY': ('Alyeska', 'United States'),
    'ARA': ('Acadiana', 'United States'),
    'ARB': ('Ann Arbor', 'United States'),
    'ARC': ('Arctic Village', 'United States'),
    'ARD': ('Alor Island', 'Indonesia'),
    'ARE': ('Arecibo', 'Puerto Rico'),
    'ARF': ('Acaricuara', 'Colombia'),
    'ARG': ('Walnut Ridge', 'United States'),
    'ARH': ('Arkhangelsk', 'Russia'),
    'ARI': ('Arica', 'Chile'),
    'ARJ': ('Arso', 'Indonesia'),
    'ARK': ('Arusha', 'Tanzania'),
    'ARL': ('Arlit', 'Niger'),
    'ARM': ('Armidale', 'Australia'),
    'ARN': ('Stockholm', 'Sweden'),
    'ARO': ('Arboletas', 'Colombia'),
    'ARP': ('Aragip', 'Papua New Guinea'),
    'ARQ': ('El Trompillo', 'Bolivia'),
    'ARR': ('Alto Rio Senguer', 'Argentina'),
    'ARS': ('Aragarcas', 'Brazil'),
    'ART': ('Watertown', 'United States'),
    'ARU': ('Aracatuba', 'Brazil'),
    'ARV': ('Lakeland', 'United States'),
    'ARW': ('Arad', 'Romania'),
    'ARX': ('Asbury Park', 'United States'),
    'ARY': ('Ararat', 'Australia'),
    'ARZ': ('N\'Zeto', 'Angola'),
    'ASA': ('Assab', 'Eritrea'),
    'ASB': ('Ashgabat', 'Turkmenistan'),
    'ASC': ('Ascension Island', 'Saint Helena'),
    'ASD': ('Andros Town', 'Bahamas'),
    'ASE': ('Aspen', 'United States'),
    'ASF': ('Astrakhan', 'Russia'),
    'ASG': ('Ashburton', 'New Zealand'),
    'ASH': ('Nashua', 'United States'),
    'ASI': ('Ascension Island', 'Saint Helena'),
    'ASJ': ('Amami', 'Japan'),
    'ASK': ('Yamoussoukro', 'Ivory Coast'),
    'ASL': ('Marshall', 'United States'),
    'ASM': ('Asmara', 'Eritrea'),
    'ASN': ('Talladega', 'United States'),
    'ASO': ('Asosa', 'Ethiopia'),
    'ASP': ('Alice Springs', 'Australia'),
    'ASQ': ('Austin', 'United States'),
    'ASR': ('Kayseri', 'Turkey'),
    'ASS': ('Arathusa', 'South Africa'),
    'AST': ('Astoria', 'United States'),
    'ASU': ('Asuncion', 'Paraguay'),
    'ASV': ('Amboseli', 'Kenya'),
    'ASW': ('Aswan', 'Egypt'),
    'ASX': ('Ashland', 'United States'),
    'ASY': ('Ashley', 'United States'),
    'ATA': ('Anta', 'Peru'),
    'ATB': ('Atqasuk', 'United States'),
    'ATC': ('Arthur\'s Town', 'Bahamas'),
    'ATD': ('Atoifi', 'Solomon Islands'),
    'ATE': ('Antlers', 'United States'),
    'ATF': ('Ambato', 'Ecuador'),
    'ATG': ('Attock', 'Pakistan'),
    'ATH': ('Athens', 'Greece'),
    'ATI': ('Artigas', 'Uruguay'),
    'ATJ': ('Antsirabe', 'Madagascar'),
    'ATK': ('Atqasuk', 'United States'),
    'ATL': ('Atlanta', 'United States'),
    'ATM': ('Altamira', 'Brazil'),
    'ATN': ('Namatanai', 'Papua New Guinea'),
    'ATO': ('Athens', 'United States'),
    'ATP': ('Aitape', 'Papua New Guinea'),
    'ATQ': ('Amritsar', 'India'),
    'ATR': ('Atar', 'Mauritania'),
    'ATS': ('Artesia', 'United States'),
    'ATT': ('Atmautluak', 'United States'),
    'ATU': ('Attu', 'United States'),
    'ATV': ('Ati', 'Chad'),
    'ATW': ('Appleton', 'United States'),
    'ATX': ('Atbasar', 'Kazakhstan'),
    'ATY': ('Watertown', 'United States'),
    'ATZ': ('Assiut', 'Egypt'),
    'AUA': ('Aruba', 'Aruba'),
    'AUB': ('Itauba', 'Brazil'),
    'AUC': ('Arauca', 'Colombia'),
    'AUD': ('Augustus Downs', 'Australia'),
    'AUE': ('Abu Rudeis', 'Egypt'),
    'AUF': ('Auxerre', 'France'),
    'AUG': ('Augusta', 'United States'),
    'AUH': ('Abu Dhabi', 'United Arab Emirates'),
    'AUI': ('Aua Island', 'Papua New Guinea'),
    'AUJ': ('Ambunti', 'Papua New Guinea'),
    'AUK': ('Alakanuk', 'United States'),
    'AUL': ('Aur Island', 'Marshall Islands'),
    'AUM': ('Austin', 'United States'),
    'AUN': ('Auburn', 'United States'),
    'AUO': ('Auburn', 'United States'),
    'AUP': ('Agaun', 'Papua New Guinea'),
    'AUQ': ('Atuona', 'French Polynesia'),
    'AUR': ('Aurillac', 'France'),
    'AUS': ('Austin', 'United States'),
    'AUT': ('Atauro', 'East Timor'),
    'AUU': ('Aurukun', 'Australia'),
    'AUV': ('Aumo', 'Papua New Guinea'),
    'AUW': ('Wausau', 'United States'),
    'AUX': ('Araguaina', 'Brazil'),
    'AUY': ('Aneityum', 'Vanuatu'),
    'AUZ': ('Aurora', 'United States'),
    'AVA': ('Anshun', 'China'),
    'AVB': ('Aviano', 'Italy'),
    'AVC': ('Ciego de Avila', 'Cuba'),
    'AVG': ('Auvergne', 'Australia'),
    'AVH': ('Arvaikheer', 'Mongolia'),
    'AVI': ('Maximo Gomez', 'Cuba'),
    'AVK': ('Arvidsjaur', 'Sweden'),
    'AVL': ('Asheville', 'United States'),
    'AVM': ('Alvo', 'Brazil'),
    'AVN': ('Avignon', 'France'),
    'AVO': ('Avon Park', 'United States'),
    'AVP': ('Wilkes-Barre', 'United States'),
    'AVQ': ('Marana', 'United States'),
    'AVR': ('Alverca', 'Portugal'),
    'AVU': ('Avu Avu', 'Solomon Islands'),
    'AVV': ('Avalon', 'Australia'),
    'AVW': ('Avra Valley', 'United States'),
    'AVX': ('Catalina Island', 'United States'),
    'AWA': ('Awassa', 'Ethiopia'),
    'AWB': ('Awaba', 'Papua New Guinea'),
    'AWD': ('Aniwa', 'Vanuatu'),
    'AWE': ('Alowe', 'Gabon'),
    'AWH': ('Awareh', 'Ethiopia'),
    'AWI': ('Awingi', 'Papua New Guinea'),
    'AWK': ('Wake Island', 'United States'),
    'AWM': ('West Memphis', 'United States'),
    'AWN': ('Alton Downs', 'Australia'),
    'AWP': ('Austral Downs', 'Australia'),
    'AWR': ('Awar', 'Papua New Guinea'),
    'AWS': ('Malikus Saleh', 'Indonesia'),
    'AWT': ('Attu', 'Greenland'),
    'AWZ': ('Ahwaz', 'Iran'),
    'AXA': ('Anguilla', 'Anguilla'),
    'AXB': ('Alexandria Bay', 'United States'),
    'AXC': ('Aramac', 'Australia'),
    'AXD': ('Alexandroupolis', 'Greece'),
    'AXE': ('Xanxere', 'Brazil'),
    'AXF': ('Alxa Right Banner', 'China'),
    'AXG': ('Algona', 'United States'),
    'AXH': ('Arutua', 'French Polynesia'),
    'AXJ': ('Amakusa', 'Japan'),
    'AXK': ('Ataq', 'Yemen'),
    'AXL': ('Alexandria', 'United States'),
    'AXM': ('Armenia', 'Colombia'),
    'AXN': ('Alexandria', 'United States'),
    'AXP': ('Spring Point', 'Bahamas'),
    'AXR': ('Arutua', 'French Polynesia'),
    'AXS': ('Altus', 'United States'),
    'AXT': ('Akita', 'Japan'),
    'AXU': ('Axum', 'Ethiopia'),
    'AXV': ('Wapakoneta', 'United States'),
    'AXX': ('Angel Fire', 'United States'),
    'AYA': ('Ayapel', 'Colombia'),
    'AYC': ('Ayacucho', 'Peru'),
    'AYD': ('Alroy Downs', 'Australia'),
    'AYE': ('Ayawasi', 'Indonesia'),
    'AYG': ('Yaguara', 'Colombia'),
    'AYI': ('Yari', 'Colombia'),
    'AYK': ('Arkalyk', 'Kazakhstan'),
    'AYL': ('Anthony Lagoon', 'Australia'),
    'AYM': ('Yas Island', 'United Arab Emirates'),
    'AYN': ('Anyang', 'China'),
    'AYO': ('Ayolas', 'Paraguay'),
    'AYP': ('Ayapel', 'Colombia'),
    'AYQ': ('Ayers Rock', 'Australia'),
    'AYR': ('Ayr', 'Australia'),
    'AYS': ('Waycross', 'United States'),
    'AYT': ('Antalya', 'Turkey'),
    'AYU': ('Aiyura', 'Papua New Guinea'),
    'AYW': ('Ayawasi', 'Indonesia'),
    'AYX': ('Ayers Rock', 'Australia'),
    'AZA': ('Phoenix', 'United States'),
    'AZB': ('Amazon Bay', 'Papua New Guinea'),
    'AZC': ('Ciego de Avila', 'Cuba'),
    'AZD': ('Yazd', 'Iran'),
    'AZE': ('Hazen Bay', 'United States'),
    'AZG': ('Apatzingan', 'Mexico'),
    'AZI': ('Abu Simbel', 'Egypt'),
    'AZN': ('Andizhan', 'Uzbekistan'),
    'AZO': ('Kalamazoo', 'United States'),
    'AZP': ('Atizapan', 'Mexico'),
    'AZR': ('Adrar', 'Algeria'),
    'AZS': ('Samana', 'Dominican Republic'),
    'AZT': ('Zapatoca', 'Colombia'),
    'AZZ': ('Ambriz', 'Angola'),
    'BAA': ('Bialla', 'Papua New Guinea'),
    'BAB': ('Beale AFB', 'United States'),
    'BAC': ('Barranca de Upia', 'Colombia'),
    'BAD': ('Barksdale AFB', 'United States'),
    'BAE': ('Barcelonnette', 'France'),
    'BAF': ('Westfield', 'United States'),
    'BAG': ('Baguio', 'Philippines'),
    'BAH': ('Bahrain', 'Bahrain'),
    'BAI': ('Buenos Aires', 'Costa Rica'),
    'BAJ': ('Bali', 'Papua New Guinea'),
    'BAK': ('Baku', 'Azerbaijan'),
    'BAL': ('Batman', 'Turkey'),
    'BAM': ('Battle Mountain', 'United States'),
    'BAN': ('Basongo', 'Congo'),
    'BAO': ('Udorn', 'Thailand'),
    'BAP': ('Baibara', 'Papua New Guinea'),
    'BAQ': ('Barranquilla', 'Colombia'),
    'BAR': ('Qionghai', 'China'),
    'BAS': ('Balalae', 'Solomon Islands'),
    'BAT': ('Barretos', 'Brazil'),
    'BAU': ('Bauru', 'Brazil'),
    'BAV': ('Baotou', 'China'),
    'BAW': ('Biawonque', 'Papua New Guinea'),
    'BAX': ('Barnaul', 'Russia'),
    'BAY': ('Baia Mare', 'Romania'),
    'BAZ': ('Barbelos', 'Brazil'),
    'BBA': ('Balmaceda', 'Chile'),
    'BBB': ('Benson', 'United States'),
    'BBC': ('Bay City', 'United States'),
    'BBD': ('Brady', 'United States'),
    'BBE': ('Big Bell', 'Australia'),
    'BBF': ('Burlington', 'United States'),
    'BBG': ('Butaritari', 'Kiribati'),
    'BBH': ('Barth', 'Germany'),
    'BBI': ('Bhubaneswar', 'India'),
    'BBJ': ('Bitburg', 'Germany'),
    'BBK': ('Kasane', 'Botswana'),
    'BBL': ('Ballera', 'Australia'),
    'BBM': ('Battambang', 'Cambodia'),
    'BBN': ('Bario', 'Malaysia'),
    'BBO': ('Berbera', 'Somalia'),
    'BBP': ('Bembridge', 'United Kingdom'),
    'BBQ': ('Barbuda', 'Antigua and Barbuda'),
    'BBR': ('Basse Terre', 'Guadeloupe'),
    'BBS': ('Blackbushe', 'United Kingdom'),
    'BBT': ('Berberati', 'Central African Republic'),
    'BBU': ('Bucharest', 'Romania'),
    'BBV': ('Bereby', 'Ivory Coast'),
    'BBW': ('Broken Bow', 'United States'),
    'BBX': ('Wings Field', 'United States'),
    'BBY': ('Bambari', 'Central African Republic'),
    'BBZ': ('Zambezi', 'Zambia'),
    'BCA': ('Baracoa', 'Cuba'),
    'BCB': ('Virginia Tech', 'United States'),
    'BCC': ('Bear Creek', 'United States'),
    'BCD': ('Bacolod', 'Philippines'),
    'BCE': ('Bryce', 'United States'),
    'BCF': ('Bouca', 'Central African Republic'),
    'BCG': ('Bemichi', 'Guyana'),
    'BCH': ('Baucau', 'East Timor'),
    'BCI': ('Barcaldine', 'Australia'),
    'BCJ': ('Baca Grande', 'United States'),
    'BCK': ('Bolwarra', 'Australia'),
    'BCL': ('Barra Colorado', 'Costa Rica'),
    'BCM': ('Bacau', 'Romania'),
    'BCN': ('Barcelona', 'Spain'),
    'BCO': ('Baco', 'Ethiopia'),
    'BCP': ('Bambu', 'Papua New Guinea'),
    'BCQ': ('Brack', 'Australia'),
    'BCR': ('Boca do Acre', 'Brazil'),
    'BCS': ('Belle Chasse', 'United States'),
    'BCT': ('Boca Raton', 'United States'),
    'BCU': ('Bauchi', 'Nigeria'),
    'BCV': ('Birchwood', 'United States'),
    'BCW': ('Benguera Island', 'Mozambique'),
    'BCX': ('Beloreck', 'Russia'),
    'BCY': ('Bulchi', 'Ethiopia'),
    'BCZ': ('Bickerton Island', 'Australia'),
    'BDA': ('Bermuda', 'Bermuda'),
    'BDB': ('Bundaberg', 'Australia'),
    'BDC': ('Barra do Corda', 'Brazil'),
    'BDD': ('Badu Island', 'Australia'),
    'BDE': ('Baudette', 'United States'),
    'BDF': ('Bradford', 'United States'),
    'BDG': ('Blanding', 'United States'),
    'BDH': ('Bandar Lengeh', 'Iran'),
    'BDI': ('Bird Island', 'Seychelles'),
    'BDJ': ('Syamsudin Noor', 'Indonesia'),
    'BDK': ('Bondoukou', 'Ivory Coast'),
    'BDL': ('Hartford', 'United States'),
    'BDM': ('Bandirma', 'Turkey'),
    'BDN': ('Talhar', 'Pakistan'),
    'BDO': ('Husein Sastranegara', 'Indonesia'),
    'BDP': ('Bhadrapur', 'Nepal'),
    'BDQ': ('Vadodara', 'India'),
    'BDR': ('Bridgeport', 'United States'),
    'BDS': ('Brindisi', 'Italy'),
    'BDT': ('Gbadolite', 'Congo'),
    'BDU': ('Bardufoss', 'Norway'),
    'BDV': ('Moba', 'Congo'),
    'BDW': ('Bedford', 'United States'),
    'BDX': ('Broadus', 'United States'),
    'BDY': ('Bandon', 'United States'),
    'BDZ': ('Baindoung', 'Papua New Guinea'),
    'BEA': ('Bereina', 'Papua New Guinea'),
    'BEB': ('Benbecula', 'United Kingdom'),
    'BEC': ('Beech Factory', 'United States'),
    'BED': ('Bedford', 'United States'),
    'BEE': ('Beagle Bay', 'Australia'),
    'BEF': ('Bluefields', 'Nicaragua'),
    'BEG': ('Belgrade', 'Serbia'),
    'BEH': ('Benton Harbor', 'United States'),
    'BEI': ('Beica', 'Ethiopia'),
    'BEJ': ('Berau', 'Indonesia'),
    'BEK': ('Barking Sands', 'United States'),
    'BEL': ('Belem', 'Brazil'),
    'BEM': ('Bossembele', 'Central African Republic'),
    'BEN': ('Benghazi', 'Libya'),
    'BEO': ('Belmont', 'Australia'),
    'BEP': ('Bellary', 'India'),
    'BEQ': ('Bury St Edmunds', 'United Kingdom'),
    'BER': ('Berlin', 'Germany'),
    'BES': ('Brest', 'France'),
    'BET': ('Bethel', 'United States'),
    'BEU': ('Bedourie', 'Australia'),
    'BEV': ('Beer Sheba', 'Israel'),
    'BEW': ('Beira', 'Mozambique'),
    'BEX': ('Benson', 'United Kingdom'),
    'BEY': ('Beirut', 'Lebanon'),
    'BEZ': ('Beru', 'Kiribati'),
    'BFA': ('Bahia Cupica', 'Colombia'),
    'BFB': ('Burao', 'Somalia'),
    'BFC': ('Bloomfield', 'Australia'),
    'BFD': ('Bradford', 'United States'),
    'BFE': ('Bielefeld', 'Germany'),
    'BFF': ('Scottsbluff', 'United States'),
    'BFG': ('Bullfrog Basin', 'United States'),
    'BFH': ('Bacacheri', 'Brazil'),
    'BFI': ('Seattle', 'United States'),
    'BFJ': ('Bijie', 'China'),
    'BFK': ('Buffalo Range', 'Zimbabwe'),
    'BFL': ('Bakersfield', 'United States'),
    'BFM': ('Mobile', 'United States'),
    'BFN': ('Bloemfontein', 'South Africa'),
    'BFO': ('Buffalo Range', 'Zimbabwe'),
    'BFP': ('Beaver Falls', 'United States'),
    'BFQ': ('Bahia Pinas', 'Panama'),
    'BFR': ('Virgil I Grissom', 'United States'),
    'BFS': ('Belfast', 'United Kingdom'),
    'BFT': ('Beaufort', 'United States'),
    'BFU': ('Bengbu', 'China'),
    'BFV': ('Buri Ram', 'Thailand'),
    'BFW': ('Soto Cano AB', 'Honduras'),
    'BFX': ('Bafoussam', 'Cameroon'),
    'BFY': ('Buffy Island', 'Papua New Guinea'),
    'BGA': ('Bucaramanga', 'Colombia'),
    'BGB': ('Booue', 'Gabon'),
    'BGC': ('Braganca', 'Portugal'),
    'BGD': ('Borger', 'United States'),
    'BGE': ('Decatur', 'United States'),
    'BGF': ('Bangui', 'Central African Republic'),
    'BGG': ('Bongouanou', 'Ivory Coast'),
    'BGH': ('Abbaye', 'Congo'),
    'BGI': ('Bridgetown', 'Barbados'),
    'BGJ': ('Borgarfjordur', 'Iceland'),
    'BGK': ('Big Creek', 'Belize'),
    'BGL': ('Balurghat', 'India'),
    'BGM': ('Binghamton', 'United States'),
    'BGN': ('Belaya Gora', 'Russia'),
    'BGO': ('Bergen', 'Norway'),
    'BGP': ('Bongo', 'Gabon'),
    'BGQ': ('Big Lake', 'United States'),
    'BGR': ('Bangor', 'United States'),
    'BGS': ('Big Spring', 'United States'),
    'BGT': ('Bagdad', 'United States'),
    'BGU': ('Bangassou', 'Central African Republic'),
    'BGV': ('Bento Goncalves', 'Brazil'),
    'BGW': ('Baghdad', 'Iraq'),
    'BGX': ('Bage', 'Brazil'),
    'BGY': ('Milan', 'Italy'),
    'BGZ': ('Braga', 'Portugal'),
    'BHA': ('Bahia de los Angeles', 'Mexico'),
    'BHB': ('Bar Harbor', 'United States'),
    'BHC': ('Bhurban', 'Pakistan'),
    'BHD': ('Belfast', 'United Kingdom'),
    'BHE': ('Blenheim', 'New Zealand'),
    'BHF': ('Bahia Cupica', 'Colombia'),
    'BHG': ('Brus Laguna', 'Honduras'),
    'BHH': ('Bisha', 'Saudi Arabia'),
    'BHI': ('Bahia Blanca', 'Argentina'),
    'BHJ': ('Bhuj', 'India'),
    'BHK': ('Bukhara', 'Uzbekistan'),
    'BHL': ('Bahia de los Angeles', 'Mexico'),
    'BHM': ('Birmingham', 'United States'),
    'BHN': ('Beihan', 'Yemen'),
    'BHO': ('Bhopal', 'India'),
    'BHP': ('Bhojpur', 'Nepal'),
    'BHQ': ('Broken Hill', 'Australia'),
    'BHR': ('Bharatpur', 'Nepal'),
    'BHS': ('Bathurst', 'Australia'),
    'BHT': ('Brighton Downs', 'Australia'),
    'BHU': ('Bhavnagar', 'India'),
    'BHV': ('Bahawalpur', 'Pakistan'),
    'BHW': ('Bhagatanwala', 'Pakistan'),
    'BHX': ('Birmingham', 'United Kingdom'),
    'BHY': ('Beihai', 'China'),
    'BHZ': ('Belo Horizonte', 'Brazil'),
    'BIA': ('Bastia', 'France'),
    'BIB': ('Baidoa', 'Somalia'),
    'BIC': ('Big Creek', 'United States'),
    'BID': ('Block Island', 'United States'),
    'BIE': ('Beatrice', 'United States'),
    'BIF': ('Biggs AAF', 'United States'),
    'BIG': ('Big Delta', 'United States'),
    'BIH': ('Bishop', 'United States'),
    'BII': ('Bikini Atoll', 'Marshall Islands'),
    'BIJ': ('Biliau', 'Papua New Guinea'),
    'BIK': ('Biak', 'Indonesia'),
    'BIL': ('Billings', 'United States'),
    'BIM': ('Bimini', 'Bahamas'),
    'BIN': ('Bamiyan', 'Afghanistan'),
    'BIO': ('Bilbao', 'Spain'),
    'BIP': ('Bulimba', 'Papua New Guinea'),
    'BIQ': ('Biarritz', 'France'),
    'BIR': ('Biratnagar', 'Nepal'),
    'BIS': ('Bismarck', 'United States'),
    'BIT': ('Baitadi', 'Nepal'),
    'BIU': ('Bildudalur', 'Iceland'),
    'BIV': ('Bria', 'Central African Republic'),
    'BIW': ('Billiluna', 'Australia'),
    'BIX': ('Biloxi', 'United States'),
    'BIY': ('Bisho', 'South Africa'),
    'BIZ': ('Bimin', 'Papua New Guinea'),
    'BJA': ('Bejaia', 'Algeria'),
    'BJB': ('Bojnord', 'Iran'),
    'BJC': ('Denver', 'United States'),
    'BJD': ('Bakkafjordur', 'Iceland'),
    'BJE': ('Baleela', 'Sudan'),
    'BJF': ('Batsfjord', 'Norway'),
    'BJG': ('Bolaang', 'Indonesia'),
    'BJH': ('Bajhang', 'Nepal'),
    'BJI': ('Bemidji', 'United States'),
    'BJJ': ('Wayne County', 'United States'),
    'BJK': ('Benjina', 'Indonesia'),
    'BJL': ('Banjul', 'Gambia'),
    'BJM': ('Bujumbura', 'Burundi'),
    'BJN': ('Bajone', 'Papua New Guinea'),
    'BJO': ('Bermejo', 'Bolivia'),
    'BJP': ('Braganca Paulista', 'Brazil'),
    'BJQ': ('Bahja', 'Yemen'),
    'BJR': ('Bahar Dar', 'Ethiopia'),
    'BJS': ('Beijing', 'China'),
    'BJT': ('Bentota River', 'Sri Lanka'),
    'BJU': ('Bajura', 'Nepal'),
    'BJV': ('Bodrum', 'Turkey'),
    'BJW': ('Bajawa', 'Indonesia'),
    'BJX': ('Leon', 'Mexico'),
    'BJY': ('Batajnica', 'Serbia'),
    'BJZ': ('Badajoz', 'Spain'),
    'BKA': ('Bykovo', 'Russia'),
    'BKB': ('Bikaner', 'India'),
    'BKC': ('Buckland', 'United States'),
    'BKD': ('Breckenridge', 'United States'),
    'BKE': ('Baker', 'United States'),
    'BKF': ('Buffalo', 'United States'),
    'BKG': ('Branson', 'United States'),
    'BKH': ('Barking Sands', 'United States'),
    'BKI': ('Kota Kinabalu', 'Malaysia'),
    'BKJ': ('Boke', 'Guinea'),
    'BKK': ('Bangkok', 'Thailand'),
    'BKL': ('Burke Lakefront', 'United States'),
    'BKM': ('Bakalalan', 'Malaysia'),
    'BKN': ('Balkanabat', 'Turkmenistan'),
    'BKO': ('Bamako', 'Mali'),
    'BKP': ('Barkly Downs', 'Australia'),
    'BKQ': ('Blackall', 'Australia'),
    'BKR': ('Bokoro', 'Chad'),
    'BKS': ('Bengkulu', 'Indonesia'),
    'BKT': ('Blackstone', 'United States'),
    'BKU': ('Betioky', 'Madagascar'),
    'BKV': ('Baki', 'Papua New Guinea'),
    'BKW': ('Beckley', 'United States'),
    'BKX': ('Brookings', 'United States'),
    'BKY': ('Bukavu', 'Congo'),
    'BKZ': ('Bukoba', 'Tanzania'),
    'BLA': ('Barcelona', 'Venezuela'),
    'BLB': ('Balboa', 'Panama'),
    'BLC': ('Bali', 'Cameroon'),
    'BLD': ('Boulder City', 'United States'),
    'BLE': ('Dala', 'Sweden'),
    'BLF': ('Bluefield', 'United States'),
    'BLG': ('Belaga', 'Malaysia'),
    'BLH': ('Blythe', 'United States'),
    'BLI': ('Bellingham', 'United States'),
    'BLJ': ('Batna', 'Algeria'),
    'BLK': ('Blackpool', 'United Kingdom'),
    'BLL': ('Billund', 'Denmark'),
    'BLM': ('Monmouth', 'United States'),
    'BLN': ('Benalla', 'Australia'),
    'BLO': ('Blonduos', 'Iceland'),
    'BLP': ('Bellavista', 'Peru'),
    'BLQ': ('Bologna', 'Italy'),
    'BLR': ('Bangalore', 'India'),
    'BLS': ('Bollon', 'Australia'),
    'BLT': ('Blackwater', 'Australia'),
    'BLU': ('Blue Canyon', 'United States'),
    'BLV': ('Belleville', 'United States'),
    'BLW': ('Bellows Field', 'United States'),
    'BLX': ('Belluno', 'Italy'),
    'BLY': ('Belmullet', 'Ireland'),
    'BLZ': ('Chileka', 'Malawi'),
    'BMA': ('Stockholm', 'Sweden'),
    'BMB': ('Bumba', 'Congo'),
    'BMC': ('Brigham City', 'United States'),
    'BMD': ('Belo', 'Madagascar'),
    'BME': ('Broome', 'Australia'),
    'BMF': ('Bakouma', 'Central African Republic'),
    'BMG': ('Bloomington', 'United States'),
    'BMH': ('Bomai', 'Papua New Guinea'),
    'BMI': ('Bloomington', 'United States'),
    'BMJ': ('Baramita', 'Guyana'),
    'BMK': ('Borkum', 'Germany'),
    'BML': ('Berlin', 'United States'),
    'BMM': ('Bitam', 'Gabon'),
    'BMN': ('Bamerny', 'Papua New Guinea'),
    'BMO': ('Bhamo', 'Myanmar'),
    'BMP': ('Brampton Island', 'Australia'),
    'BMQ': ('Bamburi', 'Kenya'),
    'BMR': ('Baltrum', 'Germany'),
    'BMS': ('Brumado', 'Brazil'),
    'BMT': ('Beaumont', 'United States'),
    'BMU': ('Bima', 'Indonesia'),
    'BMV': ('Ban Me Thuot', 'Vietnam'),
    'BMW': ('Bordj Badji Mokhtar', 'Algeria'),
    'BMX': ('Big Mountain', 'United States'),
    'BMY': ('Belep Islands', 'New Caledonia'),
    'BMZ': ('Bamu', 'Papua New Guinea'),
    'BNA': ('Nashville', 'United States'),
    'BNB': ('Boende', 'Congo'),
    'BNC': ('Beni', 'Congo'),
    'BND': ('Bandar Abbas', 'Iran'),
    'BNE': ('Brisbane', 'Australia'),
    'BNF': ('Warm Springs', 'United States'),
    'BNG': ('Banning', 'United States'),
    'BNH': ('Barnes', 'United States'),
    'BNI': ('Benin City', 'Nigeria'),
    'BNJ': ('Bonn', 'Germany'),
    'BNK': ('Ballina', 'Australia'),
    'BNL': ('Barnwell', 'United States'),
    'BNM': ('Bodinumu', 'Papua New Guinea'),
    'BNN': ('Bronnoy', 'Norway'),
    'BNO': ('Burns Lake', 'Canada'),
    'BNP': ('Bannu', 'Pakistan'),
    'BNQ': ('Baganga', 'Philippines'),
    'BNR': ('Banfora', 'Burkina Faso'),
    'BNS': ('Barinas', 'Venezuela'),
    'BNT': ('Bundi', 'Papua New Guinea'),
    'BNU': ('Blumenau', 'Brazil'),
    'BNV': ('Boana', 'Papua New Guinea'),
    'BNW': ('Boone', 'United States'),
    'BNX': ('Banja Luka', 'Bosnia and Herzegovina'),
    'BNY': ('Bellona', 'Solomon Islands'),
    'BNZ': ('Banz', 'Papua New Guinea'),
    'BOA': ('Boma', 'Congo'),
    'BOB': ('Bora Bora', 'French Polynesia'),
    'BOC': ('Bocas del Toro', 'Panama'),
    'BOD': ('Bordeaux', 'France'),
    'BOE': ('Boundji', 'Congo'),
    'BOF': ('Bolling AFB', 'United States'),
    'BOG': ('Bogota', 'Colombia'),
    'BOH': ('Bournemouth', 'United Kingdom'),
    'BOI': ('Boise', 'United States'),
    'BOJ': ('Burgas', 'Bulgaria'),
    'BOK': ('Brookings', 'United States'),
    'BOL': ('Ballykelly', 'United Kingdom'),
    'BOM': ('Mumbai', 'India'),
    'BON': ('Kralendijk', 'Netherlands Antilles'),
    'BOO': ('Bodo', 'Norway'),
    'BOP': ('Bouar', 'Central African Republic'),
    'BOQ': ('Boku', 'Papua New Guinea'),
    'BOR': ('Fontaine', 'France'),
    'BOS': ('Boston', 'United States'),
    'BOT': ('Bosset', 'Papua New Guinea'),
    'BOU': ('Bourges', 'France'),
    'BOV': ('Boang', 'Papua New Guinea'),
    'BOW': ('Bartow', 'United States'),
    'BOX': ('Borroloola', 'Australia'),
    'BOY': ('Bobo Dioulasso', 'Burkina Faso'),
    'BOZ': ('Bozoum', 'Central African Republic'),
    'BPA': ('Grumman', 'United States'),
    'BPB': ('Boridi', 'Papua New Guinea'),
    'BPC': ('Bamenda', 'Cameroon'),
    'BPD': ('Bapi', 'Papua New Guinea'),
    'BPE': ('Qinhuangdao', 'China'),
    'BPF': ('Bapi', 'Papua New Guinea'),
    'BPG': ('Barra do Garcas', 'Brazil'),
    'BPH': ('Bislig', 'Philippines'),
    'BPI': ('Big Piney', 'United States'),
    'BPJ': ('Biplane Junction', 'United States'),
    'BPK': ('Biangabip', 'Papua New Guinea'),
    'BPL': ('Bole', 'China'),
    'BPM': ('Begumpet', 'India'),
    'BPN': ('Balikpapan', 'Indonesia'),
    'BPO': ('Bokapoa', 'Papua New Guinea'),
    'BPP': ('Bislig', 'Philippines'),
    'BPQ': ('Bislig', 'Philippines'),
    'BPR': ('Borongan', 'Philippines'),
    'BPS': ('Porto Seguro', 'Brazil'),
    'BPT': ('Beaumont', 'United States'),
    'BPU': ('Beppu', 'Japan'),
    'BPV': ('Bacabal', 'Brazil'),
    'BPW': ('Besalampy', 'Madagascar'),
    'BPX': ('Qamdo', 'China'),
    'BPY': ('Besalampy', 'Madagascar'),
    'BPZ': ('Bapi', 'Papua New Guinea'),
    'BQA': ('Baler', 'Philippines'),
    'BQB': ('Busselton', 'Australia'),
    'BQC': ('Brabazon', 'United Kingdom'),
    'BQD': ('Barra do Corda', 'Brazil'),
    'BQE': ('Bubaque', 'Guinea-Bissau'),
    'BQF': ('Buri Ram', 'Thailand'),
    'BQG': ('Bogorodskoye', 'Russia'),
    'BQH': ('Biggin Hill', 'United Kingdom'),
    'BQI': ('Bagani', 'Namibia'),
    'BQJ': ('Batagay', 'Russia'),
    'BQK': ('Brunswick', 'United States'),
    'BQL': ('Boulia', 'Australia'),
    'BQM': ('Baku', 'Azerbaijan'),
    'BQN': ('Aguadilla', 'Puerto Rico'),
    'BQO': ('Bouna', 'Ivory Coast'),
    'BQP': ('Barra', 'Brazil'),
    'BQQ': ('Barra', 'United Kingdom'),
    'BQR': ('Barra', 'Brazil'),
    'BQS': ('Blagoveshchensk', 'Russia'),
    'BQT': ('Brest', 'Belarus'),
    'BQU': ('Bulawayo', 'Zimbabwe'),
    'BQV': ('Bartlett Cove', 'United States'),
    'BQW': ('Balgo Hill', 'Australia'),
    'BQX': ('Balgo Hill', 'Australia'),
    'BQY': ('Bali', 'Papua New Guinea'),
    'BQZ': ('Barra', 'Brazil'),
    'BRA': ('Barreiras', 'Brazil'),
    'BRB': ('Barreirinhas', 'Brazil'),
    'BRC': ('San Carlos de Bariloche', 'Argentina'),
    'BRD': ('Brainerd', 'United States'),
    'BRE': ('Bremen', 'Germany'),
    'BRF': ('Bradford', 'United States'),
    'BRG': ('Whitesburg', 'United States'),
    'BRH': ('Brahman', 'Australia'),
    'BRI': ('Bari', 'Italy'),
    'BRJ': ('Bright', 'Australia'),
    'BRK': ('Bourke', 'Australia'),
    'BRL': ('Burlington', 'United States'),
    'BRM': ('Barquisimeto', 'Venezuela'),
    'BRN': ('Bern', 'Switzerland'),
    'BRO': ('Brownsville', 'United States'),
    'BRP': ('Biaru', 'Papua New Guinea'),
    'BRQ': ('Brno', 'Czech Republic'),
    'BRR': ('Barra', 'United Kingdom'),
    'BRS': ('Bristol', 'United Kingdom'),
    'BRT': ('Bathurst Island', 'Australia'),
    'BRU': ('Brussels', 'Belgium'),
    'BRV': ('Bremerhaven', 'Germany'),
    'BRW': ('Barrow', 'United States'),
    'BRX': ('Maria da Fe', 'Brazil'),
    'BRY': ('Samuels Field', 'United States'),
    'BRZ': ('Borotou', 'Ivory Coast'),
    'BSA': ('Bossaso', 'Somalia'),
    'BSB': ('Brasilia', 'Brazil'),
    'BSC': ('Bahia Solano', 'Colombia'),
    'BSD': ('Baoshan', 'China'),
    'BSE': ('Sematan', 'Malaysia'),
    'BSF': ('Pointe Noire', 'Congo'),
    'BSG': ('Bata', 'Equatorial Guinea'),
    'BSH': ('Brighton', 'United Kingdom'),
    'BSI': ('Blairsville', 'United States'),
    'BSJ': ('Bairnsdale', 'Australia'),
    'BSK': ('Biskra', 'Algeria'),
    'BSL': ('Basel', 'Switzerland'),
    'BSM': ('Bishe Kola', 'Iran'),
    'BSN': ('Bossangoa', 'Central African Republic'),
    'BSO': ('Basco', 'Philippines'),
    'BSP': ('Bensbach', 'Papua New Guinea'),
    'BSQ': ('Bisbee', 'United States'),
    'BSR': ('Basra', 'Iraq'),
    'BSS': ('Balsas', 'Brazil'),
    'BST': ('Bost', 'Afghanistan'),
    'BSU': ('Basankusu', 'Congo'),
    'BSV': ('Besakoa', 'Madagascar'),
    'BSW': ('Boswell Bay', 'United States'),
    'BSX': ('Bassein', 'Myanmar'),
    'BSY': ('Bardera', 'Somalia'),
    'BSZ': ('Bartletts', 'United States'),
    'BTA': ('Bertoua', 'Cameroon'),
    'BTB': ('Betou', 'Congo'),
    'BTC': ('Batticaloa', 'Sri Lanka'),
    'BTD': ('Brunette Downs', 'Australia'),
    'BTE': ('Bonthe', 'Sierra Leone'),
    'BTF': ('Skypark', 'United States'),
    'BTG': ('Batangafo', 'Central African Republic'),
    'BTH': ('Batam', 'Indonesia'),
    'BTI': ('Barter Island', 'United States'),
    'BTJ': ('Banda Aceh', 'Indonesia'),
    'BTK': ('Bratsk', 'Russia'),
    'BTL': ('Battle Creek', 'United States'),
    'BTM': ('Butte', 'United States'),
    'BTN': ('Bennettsville', 'United States'),
    'BTO': ('Botopasie', 'Suriname'),
    'BTP': ('Butler', 'United States'),
    'BTQ': ('Butare', 'Rwanda'),
    'BTR': ('Baton Rouge', 'United States'),
    'BTS': ('Bratislava', 'Slovakia'),
    'BTT': ('Bettles', 'United States'),
    'BTU': ('Bintulu', 'Malaysia'),
    'BTV': ('Burlington', 'United States'),
    'BTW': ('Batu Licin', 'Indonesia'),
    'BTX': ('Betoota', 'Australia'),
    'BTY': ('Beatty', 'United States'),
    'BTZ': ('Bursa', 'Turkey'),
    'BUA': ('Buka', 'Papua New Guinea'),
    'BUB': ('Burwell', 'United States'),
    'BUC': ('Burketown', 'Australia'),
    'BUD': ('Budapest', 'Hungary'),
    'BUE': ('Buenaventura', 'Colombia'),
    'BUF': ('Buffalo', 'United States'),
    'BUG': ('Benguela', 'Angola'),
    'BUH': ('Bucharest', 'Romania'),
    'BUI': ('Bokondini', 'Indonesia'),
    'BUJ': ('Bouar', 'Central African Republic'),
    'BUK': ('Albuq', 'Yemen'),
    'BUL': ('Bulolo', 'Papua New Guinea'),
    'BUM': ('Butler', 'United States'),
    'BUN': ('Buenaventura', 'Colombia'),
    'BUO': ('Burao', 'Somalia'),
    'BUP': ('Bhatinda', 'India'),
    'BUQ': ('Bulawayo', 'Zimbabwe'),
    'BUR': ('Burbank', 'United States'),
    'BUS': ('Batumi', 'Georgia'),
    'BUT': ('Burton', 'United States'),
    'BUU': ('Buyo', 'Ivory Coast'),
    'BUV': ('Bella Union', 'Uruguay'),
    'BUW': ('Baubau', 'Indonesia'),
    'BUX': ('Bunia', 'Congo'),
    'BUY': ('Bunbury', 'Australia'),
    'BUZ': ('Bushehr', 'Iran'),
    'BVA': ('Paris', 'France'),
    'BVB': ('Boa Vista', 'Brazil'),
    'BVC': ('Boa Vista', 'Cape Verde'),
    'BVD': ('Beaver Inlet', 'United States'),
    'BVE': ('Brive', 'France'),
    'BVF': ('Bua', 'Fiji'),
    'BVG': ('Berlevag', 'Norway'),
    'BVH': ('Vilhena', 'Brazil'),
    'BVI': ('Birdsville', 'Australia'),
    'BVJ': ('Beroroha', 'Madagascar'),
    'BVK': ('Huacaraje', 'Bolivia'),
    'BVL': ('Baures', 'Bolivia'),
    'BVM': ('Belmonte', 'Brazil'),
    'BVN': ('Albina', 'Suriname'),
    'BVO': ('Bartlesville', 'United States'),
    'BVP': ('Bolovip', 'Papua New Guinea'),
    'BVQ': ('Batavia Downs', 'Australia'),
    'BVR': ('Esperadinha', 'Brazil'),
    'BVS': ('Breves', 'Brazil'),
    'BVT': ('Batavia Downs', 'Australia'),
    'BVU': ('Beluga', 'United States'),
    'BVV': ('Bureau Valley', 'United States'),
    'BVW': ('Batavia Downs', 'Australia'),
    'BVX': ('Batesville', 'United States'),
    'BVY': ('Beverly', 'United States'),
    'BVZ': ('Beverley Springs', 'Australia'),
    'BWA': ('Bhairawa', 'Nepal'),
    'BWB': ('Barrow Island', 'Australia'),
    'BWC': ('Brawley', 'United States'),
    'BWD': ('Brownwood', 'United States'),
    'BWE': ('Braunschweig', 'Germany'),
    'BWF': ('Walney Island', 'United Kingdom'),
    'BWG': ('Bowling Green', 'United States'),
    'BWH': ('Butterworth', 'Malaysia'),
    'BWI': ('Baltimore', 'United States'),
    'BWJ': ('Bawan', 'Papua New Guinea'),
    'BWK': ('Bol', 'Croatia'),
    'BWL': ('Blackwell', 'United States'),
    'BWM': ('Bowman', 'United States'),
    'BWN': ('Bandar Seri Begawan', 'Brunei'),
    'BWO': ('Balakovo', 'Russia'),
    'BWP': ('Bewani', 'Papua New Guinea'),
    'BWQ': ('Brewarrina', 'Australia'),
    'BWR': ('Barrow', 'United States'),
    'BWS': ('Blaine', 'United States'),
    'BWT': ('Burnie', 'Australia'),
    'BWU': ('Bankstown', 'Australia'),
    'BWV': ('Batavia', 'United States'),
    'BWW': ('Las Brujas', 'Cuba'),
    'BWX': ('Blimbingsari', 'Indonesia'),
    'BWY': ('Brawley', 'United States'),
    'BWZ': ('Beira', 'Mozambique'),
    'BXA': ('George R Carr', 'United States'),
    'BXB': ('Babo', 'Indonesia'),
    'BXC': ('Boxborough', 'United States'),
    'BXD': ('Bade', 'Indonesia'),
    'BXE': ('Bakel', 'Senegal'),
    'BXF': ('Belburn', 'Australia'),
    'BXG': ('Bendigo', 'Australia'),
    'BXH': ('Balhash', 'Kazakhstan'),
    'BXI': ('Boundiali', 'Ivory Coast'),
    'BXJ': ('Burundai', 'Kazakhstan'),
    'BXK': ('Buckeye', 'United States'),
    'BXL': ('Blue Lagoon', 'Fiji'),
    'BXM': ('Batom', 'Indonesia'),
    'BXN': ('Bodrum Imsik', 'Turkey'),
    'BXO': ('Buochs', 'Switzerland'),
    'BXP': ('Biala Podlaska', 'Poland'),
    'BXQ': ('Barranquilla', 'Colombia'),
    'BXR': ('Bam', 'Iran'),
    'BXS': ('Borrego Springs', 'United States'),
    'BXT': ('Bontang', 'Indonesia'),
    'BXU': ('Butuan', 'Philippines'),
    'BXV': ('Breiddalsvik', 'Iceland'),
    'BXW': ('Blimbingsari', 'Indonesia'),
    'BXX': ('Borama', 'Somalia'),
    'BXY': ('Baniyala', 'Australia'),
    'BXZ': ('Bunsil', 'Papua New Guinea'),
    'BYA': ('Boundary', 'United States'),
    'BYB': ('Dibaa', 'United Arab Emirates'),
    'BYC': ('Yacuiba', 'Bolivia'),
    'BYD': ('Beidah', 'Yemen'),
    'BYE': ('Burley', 'United States'),
    'BYF': ('Albert', 'France'),
    'BYG': ('Buffalo', 'United States'),
    'BYH': ('Blytheville', 'United States'),
    'BYI': ('Burley', 'United States'),
    'BYJ': ('Beja', 'Portugal'),
    'BYK': ('Bouake', 'Ivory Coast'),
    'BYL': ('Bella Yella', 'Liberia'),
    'BYM': ('Bayamo', 'Cuba'),
    'BYN': ('Bayankhongor', 'Mongolia'),
    'BYO': ('Bonito', 'Brazil'),
    'BYP': ('Barimunya', 'Australia'),
    'BYQ': ('Bunyu', 'Indonesia'),
    'BYR': ('Laeso', 'Denmark'),
    'BYS': ('Fort Irwin', 'United States'),
    'BYT': ('Bantry', 'Ireland'),
    'BYU': ('Bindlacher Berg', 'Germany'),
    'BYV': ('Beira Lake', 'Sri Lanka'),
    'BYW': ('Blakely Island', 'United States'),
    'BYX': ('Baniyala', 'Australia'),
    'BYY': ('Bay City', 'United States'),
    'BYZ': ('Belize City', 'Belize'),
    'BZA': ('Bonanza', 'Nicaragua'),
    'BZB': ('Bazaruto Island', 'Mozambique'),
    'BZC': ('Buzios', 'Brazil'),
    'BZD': ('Balranald', 'Australia'),
    'BZE': ('Belize City', 'Belize'),
    'BZF': ('Benton Field', 'United States'),
    'BZG': ('Bydgoszcz', 'Poland'),
    'BZH': ('Bumi Hills', 'Zimbabwe'),
    'BZI': ('Balikesir', 'Turkey'),
    'BZJ': ('Badu Island', 'Australia'),
    'BZK': ('Briansk', 'Russia'),
    'BZL': ('Barisal', 'Bangladesh'),
    'BZM': ('Bergen', 'Norway'),
    'BZN': ('Bozeman', 'United States'),
    'BZO': ('Bolzano', 'Italy'),
    'BZP': ('Bizant River', 'Papua New Guinea'),
    'BZQ': ('Buzau', 'Romania'),
    'BZR': ('Beziers', 'France'),
    'BZS': ('Butios', 'Papua New Guinea'),
    'BZT': ('Brazoria County', 'United States'),
    'BZU': ('Buta', 'Congo'),
    'BZV': ('Brazzaville', 'Congo'),
    'BZW': ('Barisal', 'Bangladesh'),
    'BZX': ('Busuanga', 'Philippines'),
    'BZY': ('Balti', 'Moldova'),
    'BZZ': ('Brize Norton', 'United Kingdom'),
    'CAA': ('Catacamas', 'Honduras'),
    'CAB': ('Cabinda', 'Angola'),
    'CAC': ('Cascavel', 'Brazil'),
    'CAD': ('Cadillac', 'United States'),
    'CAE': ('Columbia', 'United States'),
    'CAF': ('Carauari', 'Brazil'),
    'CAG': ('Cagliari', 'Italy'),
    'CAH': ('Ca Mau', 'Vietnam'),
    'CAI': ('Cairo', 'Egypt'),
    'CAJ': ('Canaima', 'Venezuela'),
    'CAK': ('Akron', 'United States'),
    'CAL': ('Campbeltown', 'United Kingdom'),
    'CAM': ('Camiri', 'Bolivia'),
    'CAN': ('Guangzhou', 'China'),
    'CAO': ('Clayton', 'United States'),
    'CAP': ('Cap Haitien', 'Haiti'),
    'CAQ': ('Caucasia', 'Colombia'),
    'CAR': ('Caribou', 'United States'),
    'CAS': ('Anfa', 'Morocco'),
    'CAT': ('Cat Island', 'Bahamas'),
    'CAU': ('Caruaru', 'Brazil'),
    'CAV': ('Cazombo', 'Angola'),
    'CAW': ('Campos', 'Brazil'),
    'CAX': ('Carlisle', 'United Kingdom'),
    'CAY': ('Cayenne', 'French Guiana'),
    'CAZ': ('Cobar', 'Australia'),
    'CBA': ('Corner Bay', 'United States'),
    'CBB': ('Cochabamba', 'Bolivia'),
    'CBC': ('Cherrabun', 'Australia'),
    'CBD': ('Car Nicobar', 'India'),
    'CBE': ('Cumberland', 'United States'),
    'CBF': ('Council Bluffs', 'United States'),
    'CBG': ('Cambridge', 'United Kingdom'),
    'CBH': ('Bechar', 'Algeria'),
    'CBI': ('Cape Barren Island', 'Australia'),
    'CBJ': ('Cabo Rojo', 'Dominican Republic'),
    'CBK': ('Colby', 'United States'),
    'CBL': ('Ciudad Bolivar', 'Venezuela'),
    'CBM': ('Columbus', 'United States'),
    'CBN': ('Cirebon', 'Indonesia'),
    'CBO': ('Cotabato', 'Philippines'),
    'CBP': ('Coimbra', 'Portugal'),
    'CBQ': ('Calabar', 'Nigeria'),
    'CBR': ('Canberra', 'Australia'),
    'CBS': ('Oro Negro', 'Colombia'),
    'CBT': ('Catumbela', 'Angola'),
    'CBU': ('Cottbus', 'Germany'),
    'CBV': ('Coban', 'Guatemala'),
    'CBW': ('Campo Mourao', 'Brazil'),
    'CBX': ('Condobolin', 'Australia'),
    'CBY': ('Canobie', 'Australia'),
    'CBZ': ('Cabin Creek', 'United States'),
    'CCA': ('Clinton', 'United States'),
    'CCB': ('Cable', 'United States'),
    'CCC': ('Cayo Coco', 'Cuba'),
    'CCD': ('Century', 'United States'),
    'CCE': ('Chernomorskoye', 'Russia'),
    'CCF': ('Carcassonne', 'France'),
    'CCG': ('Crane Island', 'United States'),
    'CCH': ('Chile Chico', 'Chile'),
    'CCI': ('Concordia', 'Brazil'),
    'CCJ': ('Calicut', 'India'),
    'CCK': ('Cocos Islands', 'Cocos Islands'),
    'CCL': ('Chinchilla', 'Australia'),
    'CCM': ('Criciuma', 'Brazil'),
    'CCN': ('Chakcharan', 'Afghanistan'),
    'CCO': ('Carimagua', 'Colombia'),
    'CCP': ('Concepcion', 'Chile'),
    'CCQ': ('Cachoeira', 'Brazil'),
    'CCR': ('Concord', 'United States'),
    'CCS': ('Caracas', 'Venezuela'),
    'CCT': ('Colonia Catriel', 'Argentina'),
    'CCU': ('Kolkata', 'India'),
    'CCV': ('Craig Cove', 'Vanuatu'),
    'CCW': ('Cowell', 'Australia'),
    'CCX': ('Caceres', 'Brazil'),
    'CCY': ('Charles City', 'United States'),
    'CCZ': ('Chub Cay', 'Bahamas'),
    'CDA': ('Cooinda', 'Australia'),
    'CDB': ('Cold Bay', 'United States'),
    'CDC': ('Cedar City', 'United States'),
    'CDD': ('Cauquira', 'Honduras'),
    'CDE': ('Chengde', 'China'),
    'CDF': ('Cortez', 'United States'),
    'CDG': ('Paris', 'France'),
    'CDH': ('Camden', 'United States'),
    'CDI': ('Cachoeiro de Itapemirim', 'Brazil'),
    'CDJ': ('Conceicao do Araguaia', 'Brazil'),
    'CDK': ('Cedar Key', 'United States'),
    'CDL': ('Candle', 'United States'),
    'CDM': ('Camden', 'Australia'),
    'CDN': ('Woodward Field', 'United States'),
    'CDO': ('Cradock', 'South Africa'),
    'CDP': ('Cuddapah', 'India'),
    'CDQ': ('Croydon', 'Australia'),
    'CDR': ('Chadron', 'United States'),
    'CDS': ('Childress', 'United States'),
    'CDT': ('Castellon de la Plana', 'Spain'),
    'CDU': ('Camden', 'Australia'),
    'CDV': ('Cordova', 'United States'),
    'CDW': ('Caldwell', 'United States'),
    'CDX': ('Cadellia', 'Australia'),
    'CDY': ('Cagayan de Sulu', 'Philippines'),
    'CDZ': ('Cadiz', 'Spain'),
    'CEA': ('Cessna', 'United States'),
    'CEB': ('Cebu', 'Philippines'),
    'CEC': ('Crescent City', 'United States'),
    'CED': ('Ceduna', 'Australia'),
    'CEE': ('Cherepovets', 'Russia'),
    'CEF': ('Westover', 'United States'),
    'CEG': ('Chester', 'United Kingdom'),
    'CEH': ('Chelinda', 'Malawi'),
    'CEI': ('Chiang Rai', 'Thailand'),
    'CEJ': ('Chernigov', 'Ukraine'),
    'CEK': ('Chelyabinsk', 'Russia'),
    'CEL': ('Cape Eleuthera', 'Bahamas'),
    'CEM': ('Central', 'United States'),
    'CEN': ('Ciudad Obregon', 'Mexico'),
    'CEO': ('Waco', 'United States'),
    'CEP': ('Concepcion', 'Bolivia'),
    'CEQ': ('Cannes', 'France'),
    'CER': ('Cherbourg', 'France'),
    'CES': ('Cessnock', 'Australia'),
    'CET': ('Cholet', 'France'),
    'CEU': ('Clemson', 'United States'),
    'CEV': ('Connersville', 'United States'),
    'CEW': ('Crestview', 'United States'),
    'CEX': ('Chena Hot Springs', 'United States'),
    'CEY': ('Murray Calloway County', 'United States'),
    'CEZ': ('Cortez', 'United States'),
    'CFA': ('Coffee Point', 'United States'),
    'CFB': ('Cabo Frio', 'Brazil'),
    'CFC': ('Cacador', 'Brazil'),
    'CFD': ('Bryan', 'United States'),
    'CFE': ('Clermont-Ferrand', 'France'),
    'CFF': ('Cafunfo', 'Angola'),
    'CFG': ('Jaime Gonzalez', 'Cuba'),
    'CFH': ('Clifton Hills', 'Australia'),
    'CFI': ('Camfield', 'Australia'),
    'CFJ': ('Caen', 'France'),
    'CFK': ('Abidjan', 'Ivory Coast'),
    'CFL': ('Coldfoot', 'United States'),
    'CFM': ('Carrickfinn', 'Ireland'),
    'CFN': ('Donegal', 'Ireland'),
    'CFO': ('Confresa', 'Brazil'),
    'CFP': ('Carpentaria Downs', 'Australia'),
    'CFQ': ('Creston', 'Canada'),
    'CFR': ('Caen', 'France'),
    'CFS': ('Coffs Harbour', 'Australia'),
    'CFT': ('Clifton', 'Australia'),
    'CFU': ('Corfu', 'Greece'),
    'CFV': ('Coffeyville', 'United States'),
    'CFW': ('Crofton', 'United States'),
    'CFX': ('Coldfoot', 'United States'),
    'CFY': ('Clermont', 'Australia'),
    'CFZ': ('Clifton', 'Australia'),
    'CGA': ('Craig', 'United States'),
    'CGB': ('Cuiaba', 'Brazil'),
    'CGC': ('Cape Gloucester', 'Papua New Guinea'),
    'CGD': ('Changde', 'China'),
    'CGE': ('Cambridge', 'United States'),
    'CGF': ('Cleveland', 'United States'),
    'CGG': ('Casiguran', 'Philippines'),
    'CGH': ('Sao Paulo', 'Brazil'),
    'CGI': ('Cape Girardeau', 'United States'),
    'CGJ': ('Chingola', 'Zambia'),
    'CGK': ('Jakarta', 'Indonesia'),
    'CGL': ('Cologne', 'Germany'),
    'CGM': ('Camiguin', 'Philippines'),
    'CGN': ('Cologne', 'Germany'),
    'CGO': ('Zhengzhou', 'China'),
    'CGP': ('Chittagong', 'Bangladesh'),
    'CGQ': ('Changchun', 'China'),
    'CGR': ('Campo Grande', 'Brazil'),
    'CGS': ('College Park', 'United States'),
    'CGT': ('Chinguitti', 'Mauritania'),
    'CGU': ('Ciudad Guayana', 'Venezuela'),
    'CGV': ('Caiguna', 'Australia'),
    'CGW': ('Caingwaters', 'Australia'),
    'CGX': ('Chicago', 'United States'),
    'CGY': ('Cagayan de Oro', 'Philippines'),
    'CGZ': ('Casa Grande', 'United States'),
    'CHA': ('Chattanooga', 'United States'),
    'CHB': ('Chilas', 'Pakistan'),
    'CHC': ('Christchurch', 'New Zealand'),
    'CHD': ('Chandler', 'United States'),
    'CHE': ('Caherciveen', 'Ireland'),
    'CHF': ('Chinhae', 'South Korea'),
    'CHG': ('Chaoyang', 'China'),
    'CHH': ('Chachapoyas', 'Peru'),
    'CHI': ('Chicago', 'United States'),
    'CHJ': ('Chipinge', 'Zimbabwe'),
    'CHK': ('Chickasha', 'United States'),
    'CHL': ('Challis', 'United States'),
    'CHM': ('Chimbote', 'Peru'),
    'CHN': ('Jeonju', 'South Korea'),
    'CHO': ('Charlottesville', 'United States'),
    'CHP': ('Circle Hot Springs', 'United States'),
    'CHQ': ('Chania', 'Greece'),
    'CHR': ('Chateauroux', 'France'),
    'CHS': ('Charleston', 'United States'),
    'CHT': ('Karewa', 'New Zealand'),
    'CHU': ('Chuathbaluk', 'United States'),
    'CHV': ('Chaves', 'Portugal'),
    'CHW': ('Jiuquan', 'China'),
    'CHX': ('Changuinola', 'Panama'),
    'CHY': ('Choiseul Bay', 'Solomon Islands'),
    'CHZ': ('Chiloquin', 'United States'),
    'CIA': ('Rome', 'Italy'),
    'CIB': ('Catalina Island', 'United States'),
    'CIC': ('Chico', 'United States'),
    'CID': ('Cedar Rapids', 'United States'),
    'CIE': ('Collie', 'Australia'),
    'CIF': ('Chifeng', 'China'),
    'CIG': ('Craig', 'United States'),
    'CIH': ('Changzhi', 'China'),
    'CII': ('Choiseul Bay', 'Solomon Islands'),
    'CIJ': ('Cobija', 'Bolivia'),
    'CIK': ('Chalkyitsik', 'United States'),
    'CIL': ('Council', 'United States'),
    'CIM': ('Cimitarra', 'Colombia'),
    'CIN': ('Carroll', 'United States'),
    'CIO': ('Concepcion', 'Colombia'),
    'CIP': ('Chipata', 'Zambia'),
    'CIQ': ('Chiquimula', 'Guatemala'),
    'CIR': ('Cairo', 'United States'),
    'CIS': ('Canton Island', 'Kiribati'),
    'CIT': ('Shimkent', 'Kazakhstan'),
    'CIU': ('Sault Ste Marie', 'United States'),
    'CIV': ('Chomley', 'Australia'),
    'CIW': ('Canouan Island', 'Saint Vincent and the Grenadines'),
    'CIX': ('Cornel Ruiz', 'Peru'),
    'CIY': ('Comiso', 'Italy'),
    'CIZ': ('Coari', 'Brazil'),
    'CJA': ('Cajamarca', 'Peru'),
    'CJB': ('Coimbatore', 'India'),
    'CJC': ('Calama', 'Chile'),
    'CJD': ('Candilejas', 'Colombia'),
    'CJE': ('Chongjin', 'North Korea'),
    'CJF': ('Coondewanna', 'Australia'),
    'CJG': ('Chitral', 'Pakistan'),
    'CJH': ('Chilko Lake', 'Canada'),
    'CJI': ('Ciudad Real', 'Spain'),
    'CJJ': ('Cheongju', 'South Korea'),
    'CJK': ('Crooked Creek', 'United States'),
    'CJL': ('Chitral', 'Pakistan'),
    'CJM': ('Chumphon', 'Thailand'),
    'CJN': ('El Cajon', 'United States'),
    'CJO': ('Copiapo', 'Chile'),
    'CJP': ('Chitipa', 'Malawi'),
    'CJQ': ('Chitral', 'Pakistan'),
    'CJR': ('Culiacan', 'Mexico'),
    'CJS': ('Ciudad Juarez', 'Mexico'),
    'CJT': ('Comitan', 'Mexico'),
    'CJU': ('Jeju', 'South Korea'),
    'CJV': ('Chitral', 'Pakistan'),
    'CJW': ('Chitral', 'Pakistan'),
    'CJX': ('Chitral', 'Pakistan'),
    'CJY': ('Chitral', 'Pakistan'),
    'CJZ': ('Corazon de Jesus', 'Colombia'),
    'CKA': ('Kegaska', 'Canada'),
    'CKB': ('Clarksburg', 'United States'),
    'CKC': ('Cherkassy', 'Ukraine'),
    'CKD': ('Crooked Island', 'Bahamas'),
    'CKE': ('Clear Lake', 'United States'),
    'CKF': ('Crisp County', 'United States'),
    'CKG': ('Chongqing', 'China'),
    'CKH': ('Chokurdah', 'Russia'),
    'CKI': ('Croker Island', 'Australia'),
    'CKJ': ('Canakkale', 'Turkey'),
    'CKK': ('Cherokee', 'United States'),
    'CKL': ('Chkalovsky', 'Russia'),
    'CKM': ('Fletcher Field', 'United States'),
    'CKN': ('Crookston', 'United States'),
    'CKO': ('Cornelio Procopio', 'Brazil'),
    'CKP': ('Chkalovsky', 'Russia'),
    'CKQ': ('Chongqing', 'China'),
    'CKR': ('Crane Island', 'United States'),
    'CKS': ('Carajas', 'Brazil'),
    'CKT': ('Sarakhs', 'Iran'),
    'CKU': ('Cordova', 'United States'),
    'CKV': ('Clarksville', 'United States'),
    'CKW': ('Christmas Creek', 'Australia'),
    'CKX': ('Chicken', 'United States'),
    'CKY': ('Conakry', 'Guinea'),
    'CKZ': ('Canakkale', 'Turkey'),
    'CLA': ('Comilla', 'Bangladesh'),
    'CLB': ('Castlebar', 'Ireland'),
    'CLC': ('Clear Lake', 'United States'),
    'CLD': ('Carlsbad', 'United States'),
    'CLE': ('Cleveland', 'United States'),
    'CLF': ('Coltishall', 'United Kingdom'),
    'CLG': ('Coalinga', 'United States'),
    'CLH': ('Coolah', 'Australia'),
    'CLI': ('Clintonville', 'United States'),
    'CLJ': ('Cluj-Napoca', 'Romania'),
    'CLK': ('Clinton', 'United States'),
    'CLL': ('College Station', 'United States'),
    'CLM': ('Port Angeles', 'United States'),
    'CLN': ('Carolina', 'Brazil'),
    'CLO': ('Cali', 'Colombia'),
    'CLP': ('Clarks Point', 'United States'),
    'CLQ': ('Colima', 'Mexico'),
    'CLR': ('Calipatria', 'United States'),
    'CLS': ('Chehalis', 'United States'),
    'CLT': ('Charlotte', 'United States'),
    'CLU': ('Columbus', 'United States'),
    'CLV': ('Caldas Novas', 'Brazil'),
    'CLW': ('Clearwater', 'United States'),
    'CLX': ('Clorinda', 'Argentina'),
    'CLY': ('Calvi', 'France'),
    'CLZ': ('Calabozo', 'Venezuela'),
    'CMA': ('Cunnamulla', 'Australia'),
    'CMB': ('Colombo', 'Sri Lanka'),
    'CMC': ('Camocim', 'Brazil'),
    'CMD': ('Cootamundra', 'Australia'),
    'CME': ('Ciudad del Carmen', 'Mexico'),
    'CMF': ('Chambery', 'France'),
    'CMG': ('Corumba', 'Brazil'),
    'CMH': ('Columbus', 'United States'),
    'CMI': ('Champaign', 'United States'),
    'CMJ': ('Chi Mei', 'Taiwan'),
    'CMK': ('Club Makokola', 'Malawi'),
    'CML': ('Camooweal', 'Australia'),
    'CMM': ('Carmelita', 'Guatemala'),
    'CMN': ('Casablanca', 'Morocco'),
    'CMO': ('Obbia', 'Somalia'),
    'CMP': ('Santana do Araguaia', 'Brazil'),
    'CMQ': ('Clermont', 'Australia'),
    'CMR': ('Colmar', 'France'),
    'CMS': ('Scusciuban', 'Somalia'),
    'CMT': ('Cameta', 'Brazil'),
    'CMU': ('Chimbu', 'Papua New Guinea'),
    'CMV': ('Coromandel', 'New Zealand'),
    'CMW': ('Camaguey', 'Cuba'),
    'CMX': ('Hancock', 'United States'),
    'CMY': ('Sparta', 'United States'),
    'CMZ': ('Caia', 'Mozambique'),
    'CNA': ('Cananea', 'Mexico'),
    'CNB': ('Coonamble', 'Australia'),
    'CNC': ('Coconut Island', 'Australia'),
    'CND': ('Constanta', 'Romania'),
    'CNE': ('Canon City', 'United States'),
    'CNF': ('Belo Horizonte', 'Brazil'),
    'CNG': ('Cognac', 'France'),
    'CNH': ('Claremont', 'United States'),
    'CNI': ('Changhai', 'China'),
    'CNJ': ('Cloncurry', 'Australia'),
    'CNK': ('Concordia', 'United States'),
    'CNL': ('Sindal', 'Denmark'),
    'CNM': ('Carlsbad', 'United States'),
    'CNN': ('Chulman', 'Russia'),
    'CNO': ('Chino', 'United States'),
    'CNP': ('Neerlerit Inaat', 'Greenland'),
    'CNQ': ('Corrientes', 'Argentina'),
    'CNR': ('Chanaral', 'Chile'),
    'CNS': ('Cairns', 'Australia'),
    'CNT': ('Charata', 'Argentina'),
    'CNU': ('Chanute', 'United States'),
    'CNV': ('Canavieiras', 'Brazil'),
    'CNW': ('Waco', 'United States'),
    'CNX': ('Chiang Mai', 'Thailand'),
    'CNY': ('Moab', 'United States'),
    'CNZ': ('Cangamba', 'Angola'),
    'COA': ('Columbia', 'United States'),
    'COB': ('Coolibah', 'Australia'),
    'COC': ('Concordia', 'Argentina'),
    'COD': ('Cody', 'United States'),
    'COE': ('Coeur d\'Alene', 'United States'),
    'COF': ('Cocoa', 'United States'),
    'COG': ('Condoto', 'Colombia'),
    'COH': ('Cooch Behar', 'India'),
    'COI': ('Merritt Island', 'United States'),
    'COJ': ('Coonabarabran', 'Australia'),
    'COK': ('Cochin', 'India'),
    'COL': ('Coll Island', 'United Kingdom'),
    'COM': ('Coleman', 'United States'),
    'CON': ('Concord', 'United States'),
    'COO': ('Cotonou', 'Benin'),
    'COP': ('Cooperstown', 'United States'),
    'COQ': ('Choibalsan', 'Mongolia'),
    'COR': ('Cordoba', 'Argentina'),
    'COS': ('Colorado Springs', 'United States'),
    'COT': ('Cotulla', 'United States'),
    'COU': ('Columbia', 'United States'),
    'COV': ('Covilha', 'Portugal'),
    'COW': ('Coquimbo', 'Chile'),
    'COX': ('Congo Town', 'Bahamas'),
    'COY': ('Coolawanyah', 'Australia'),
    'COZ': ('Constanza', 'Dominican Republic'),
    'CPA': ('Cape Palmas', 'Liberia'),
    'CPB': ('Capurgana', 'Colombia'),
    'CPC': ('Chapelco', 'Argentina'),
    'CPD': ('Coober Pedy', 'Australia'),
    'CPE': ('Campeche', 'Mexico'),
    'CPF': ('Cepu', 'Indonesia'),
    'CPG': ('Carmen de Patagones', 'Argentina'),
    'CPH': ('Copenhagen', 'Denmark'),
    'CPI': ('Cape Orford', 'Australia'),
    'CPJ': ('Campina Grande', 'Brazil'),
    'CPK': ('Chesapeake', 'United States'),
    'CPL': ('Chaparral', 'Colombia'),
    'CPM': ('Compton', 'United States'),
    'CPN': ('Cape Rodney', 'Papua New Guinea'),
    'CPO': ('Copiapo', 'Chile'),
    'CPP': ('Coposa', 'Chile'),
    'CPQ': ('Campinas', 'Brazil'),
    'CPR': ('Casper', 'United States'),
    'CPS': ('St Louis', 'United States'),
    'CPT': ('Cape Town', 'South Africa'),
    'CPU': ('Cururupu', 'Brazil'),
    'CPV': ('Campina Grande', 'Brazil'),
    'CPW': ('Campbellpore', 'Pakistan'),
    'CPX': ('Culebra', 'Puerto Rico'),
    'CPY': ('Calbayog', 'Philippines'),
    'CPZ': ('Calpulalpan', 'Mexico'),
    'CQA': ('Canarana', 'Brazil'),
    'CQB': ('Calabar', 'Nigeria'),
    'CQC': ('Caucete', 'Argentina'),
    'CQD': ('Shahre-Kord', 'Iran'),
    'CQE': ('Chiquicamata', 'Chile'),
    'CQF': ('Calais', 'France'),
    'CQG': ('Changqing', 'China'),
    'CQH': ('Changchun', 'China'),
    'CQI': ('Changchun', 'China'),
    'CQJ': ('Changchun', 'China'),
    'CQK': ('Changchun', 'China'),
    'CQL': ('Changchun', 'China'),
    'CQM': ('Ciudad Real', 'Spain'),
    'CQN': ('Changchun', 'China'),
    'CQO': ('Changchun', 'China'),
    'CQP': ('Cape Flattery', 'Australia'),
    'CQQ': ('Changchun', 'China'),
    'CQR': ('Changchun', 'China'),
    'CQS': ('Costa Marques', 'Brazil'),
    'CQT': ('Caquetania', 'Colombia'),
    'CQU': ('Changchun', 'China'),
    'CQV': ('Changchun', 'China'),
    'CQW': ('Changchun', 'China'),
    'CQX': ('Changchun', 'China'),
    'CQY': ('Changchun', 'China'),
    'CQZ': ('Changchun', 'China'),
    'CRA': ('Craiova', 'Romania'),
    'CRB': ('Collarenebri', 'Australia'),
    'CRC': ('Cartago', 'Colombia'),
    'CRD': ('Comodoro Rivadavia', 'Argentina'),
    'CRE': ('Grand Strand', 'United States'),
    'CRF': ('Carnot', 'Central African Republic'),
    'CRG': ('Jacksonville', 'United States'),
    'CRH': ('Cherribah', 'Australia'),
    'CRI': ('Crooked Island', 'Bahamas'),
    'CRJ': ('Coorabie', 'Australia'),
    'CRK': ('Clark', 'Philippines'),
    'CRL': ('Brussels', 'Belgium'),
    'CRM': ('Catarman', 'Philippines'),
    'CRN': ('Cromarty', 'United Kingdom'),
    'CRO': ('Corcoran', 'United States'),
    'CRP': ('Corpus Christi', 'United States'),
    'CRQ': ('Caravelas', 'Brazil'),
    'CRR': ('Ceres', 'Argentina'),
    'CRS': ('Corsicana', 'United States'),
    'CRT': ('Crossett', 'United States'),
    'CRU': ('Carriacou Island', 'Grenada'),
    'CRV': ('Crotone', 'Italy'),
    'CRW': ('Charleston', 'United States'),
    'CRX': ('Corinth', 'United States'),
    'CRY': ('Carlton Hill', 'Australia'),
    'CRZ': ('Turkmenabad', 'Turkmenistan'),
    'CSA': ('Colonsay', 'United Kingdom'),
    'CSB': ('Caransebes', 'Romania'),
    'CSC': ('Canas', 'Costa Rica'),
    'CSD': ('Cresswell Downs', 'Australia'),
    'CSE': ('Crested Butte', 'United States'),
    'CSF': ('Creil', 'France'),
    'CSG': ('Columbus', 'United States'),
    'CSH': ('Solovetsky', 'Russia'),
    'CSI': ('Casino', 'Australia'),
    'CSJ': ('Cap Skiring', 'Senegal'),
    'CSK': ('Cap Skirring', 'Senegal'),
    'CSL': ('San Luis Obispo', 'United States'),
    'CSM': ('Clinton', 'United States'),
    'CSN': ('Carson City', 'United States'),
    'CSO': ('Cochstedt', 'Germany'),
    'CSP': ('Cape Spencer', 'Australia'),
    'CSQ': ('Creston', 'United States'),
    'CSR': ('Casuarito', 'Colombia'),
    'CSS': ('Cassilandia', 'Brazil'),
    'CST': ('Castaway', 'Fiji'),
    'CSU': ('Santa Cruz do Sul', 'Brazil'),
    'CSV': ('Crossville', 'United States'),
    'CSW': ('Colorado do Oeste', 'Brazil'),
    'CSX': ('Changsha', 'China'),
    'CSY': ('Cheboksary', 'Russia'),
    'CSZ': ('Coronel Suarez', 'Argentina'),
    'CTA': ('Catania', 'Italy'),
    'CTB': ('Cut Bank', 'United States'),
    'CTC': ('Catamarca', 'Argentina'),
    'CTD': ('Chitre', 'Panama'),
    'CTE': ('Carti', 'Panama'),
    'CTF': ('Coatepeque', 'Guatemala'),
    'CTG': ('Cartagena', 'Colombia'),
    'CTH': ('Chester', 'United States'),
    'CTI': ('Cuito Cuanavale', 'Angola'),
    'CTJ': ('Cooter', 'United States'),
    'CTK': ('Canton', 'United States'),
    'CTL': ('Charleville', 'Australia'),
    'CTM': ('Chetumal', 'Mexico'),
    'CTN': ('Cooktown', 'Australia'),
    'CTO': ('Calverton', 'United States'),
    'CTP': ('Carutapera', 'Brazil'),
    'CTQ': ('Santa Vitoria do Palmar', 'Brazil'),
    'CTR': ('Cattle Creek', 'Australia'),
    'CTS': ('Sapporo', 'Japan'),
    'CTT': ('Le Castellet', 'France'),
    'CTU': ('Chengdu', 'China'),
    'CTV': ('Charlottesville', 'United States'),
    'CTW': ('Cottonwood', 'United States'),
    'CTX': ('Cortland', 'United States'),
    'CTY': ('Cross City', 'United States'),
    'CTZ': ('Clinton', 'United States'),
    'CUA': ('Ciudad Constitucion', 'Mexico'),
    'CUB': ('Columbia', 'United States'),
    'CUC': ('Cucuta', 'Colombia'),
    'CUD': ('Caloundra', 'Australia'),
    'CUE': ('Cuenca', 'Ecuador'),
    'CUF': ('Levaldigi', 'Italy'),
    'CUG': ('Cudal', 'Australia'),
    'CUH': ('Cushing', 'United States'),
    'CUI': ('Curillo', 'Colombia'),
    'CUJ': ('Culion', 'Philippines'),
    'CUK': ('Caye Caulker', 'Belize'),
    'CUL': ('Culiacan', 'Mexico'),
    'CUM': ('Cumana', 'Venezuela'),
    'CUN': ('Cancun', 'Mexico'),
    'CUO': ('Caruru', 'Colombia'),
    'CUP': ('Carupano', 'Venezuela'),
    'CUQ': ('Coen', 'Australia'),
    'CUR': ('Curacao', 'Netherlands Antilles'),
    'CUS': ('Columbus', 'United States'),
    'CUT': ('Cutral-Co', 'Argentina'),
    'CUU': ('Chihuahua', 'Mexico'),
    'CUV': ('Casigua', 'Venezuela'),
    'CUW': ('Cube Cove', 'United States'),
    'CUX': ('Cuddihy Field', 'United States'),
    'CUY': ('Cue', 'Australia'),
    'CUZ': ('Cuzco', 'Peru'),
    'CVA': ('Covenas', 'Colombia'),
    'CVB': ('Chungribu', 'Papua New Guinea'),
    'CVC': ('Cleve', 'Australia'),
    'CVD': ('Clovis', 'United States'),
    'CVE': ('Covenas', 'Colombia'),
    'CVF': ('Courchevel', 'France'),
    'CVG': ('Cincinnati', 'United States'),
    'CVH': ('Caviahue', 'Argentina'),
    'CVI': ('Caleta Olivia', 'Argentina'),
    'CVJ': ('Cuernavaca', 'Mexico'),
    'CVK': ('Clarksville', 'United States'),
    'CVL': ('Cape Vogel', 'Papua New Guinea'),
    'CVM': ('Ciudad Victoria', 'Mexico'),
    'CVN': ('Clovis', 'United States'),
    'CVO': ('Corvallis', 'United States'),
    'CVP': ('Covington', 'United States'),
    'CVQ': ('Carnarvon', 'Australia'),
    'CVR': ('Hughes', 'United States'),
    'CVS': ('Cannon AFB', 'United States'),
    'CVT': ('Coventry', 'United Kingdom'),
    'CVU': ('Corvo Island', 'Portugal'),
    'CVV': ('Carnarvon', 'South Africa'),
    'CVW': ('Carnarvon', 'Australia'),
    'CVX': ('Charlevoix', 'United States'),
    'CVY': ('Coventry', 'United States'),
    'CVZ': ('Carvajal', 'Colombia'),
    'CWA': ('Wausau', 'United States'),
    'CWB': ('Curitiba', 'Brazil'),
    'CWC': ('Chernovtsy', 'Ukraine'),
    'CWD': ('Caledon', 'South Africa'),
    'CWE': ('Cowarie', 'Australia'),
    'CWF': ('Chennault', 'United States'),
    'CWG': ('Callaway Gardens', 'United States'),
    'CWH': ('Cachimbo', 'Brazil'),
    'CWI': ('Clinton', 'United States'),
    'CWJ': ('Cangyuan', 'China'),
    'CWK': ('Chewelah', 'United States'),
    'CWL': ('Cardiff', 'United Kingdom'),
    'CWM': ('Cowra', 'Australia'),
    'CWN': ('Chisana', 'United States'),
    'CWO': ('Chewore', 'Zimbabwe'),
    'CWP': ('Campbellpore', 'Pakistan'),
    'CWQ': ('Chewore', 'Zimbabwe'),
    'CWR': ('Cowarie', 'Australia'),
    'CWS': ('Center Island', 'United States'),
    'CWT': ('Cowra', 'Australia'),
    'CWU': ('Chewore', 'Zimbabwe'),
    'CWV': ('Carnarvon', 'Australia'),
    'CWW': ('Corowa', 'Australia'),
    'CWX': ('Cochrane', 'Chile'),
    'CWY': ('Corowa', 'Australia'),
    'CWZ': ('Cruzeiro do Sul', 'Brazil'),
    'CXA': ('Caicara del Orinoco', 'Venezuela'),
    'CXB': ('Cox\'s Bazar', 'Bangladesh'),
    'CXC': ('Chitina', 'United States'),
    'CXD': ('Christmas Creek', 'Australia'),
    'CXE': ('Chase', 'Canada'),
    'CXF': ('Coldfoot', 'United States'),
    'CXG': ('Chitral', 'Pakistan'),
    'CXH': ('Coal Harbour', 'Canada'),
    'CXI': ('Christmas Island', 'Kiribati'),
    'CXJ': ('Caxias do Sul', 'Brazil'),
    'CXK': ('Chitral', 'Pakistan'),
    'CXL': ('Calexico', 'United States'),
    'CXM': ('Chitral', 'Pakistan'),
    'CXN': ('Candala', 'Somalia'),
    'CXO': ('Conroe', 'United States'),
    'CXP': ('Tunggul Wulung', 'Indonesia'),
    'CXQ': ('Christmas Creek', 'Australia'),
    'CXR': ('Cam Ranh', 'Vietnam'),
    'CXS': ('Chitral', 'Pakistan'),
    'CXT': ('Charters Towers', 'Australia'),
    'CXU': ('Chitral', 'Pakistan'),
    'CXV': ('Chitral', 'Pakistan'),
    'CXW': ('Chitral', 'Pakistan'),
    'CXX': ('Chitral', 'Pakistan'),
    'CXY': ('Cat Cay', 'Bahamas'),
    'CXZ': ('Chitral', 'Pakistan'),
    'CYA': ('Les Cayes', 'Haiti'),
    'CYB': ('Cayman Brac', 'Cayman Islands'),
    'CYC': ('Caye Chapel', 'Belize'),
    'CYD': ('Chengde', 'China'),
    'CYE': ('Crystal Lake', 'United States'),
    'CYF': ('Chefornak', 'United States'),
    'CYG': ('Corryong', 'Australia'),
    'CYH': ('Choiseul Bay', 'Solomon Islands'),
    'CYI': ('Chiayi', 'Taiwan'),
    'CYJ': ('Calbayog', 'Philippines'),
    'CYK': ('Caye Chapel', 'Belize'),
    'CYL': ('Coyoles', 'Honduras'),
    'CYM': ('Chatham', 'United States'),
    'CYN': ('Canyonlands Field', 'United States'),
    'CYO': ('Cayo Largo del Sur', 'Cuba'),
    'CYP': ('Calbayog', 'Philippines'),
    'CYQ': ('Coyhaique', 'Chile'),
    'CYR': ('Laguna de Los Patos', 'Colombia'),
    'CYS': ('Cheyenne', 'United States'),
    'CYT': ('Yakataga', 'United States'),
    'CYU': ('Cuyo', 'Philippines'),
    'CYV': ('Calbayog', 'Philippines'),
    'CYW': ('Celaya', 'Mexico'),
    'CYX': ('Cherskiy', 'Russia'),
    'CYY': ('Chateauguay', 'Canada'),
    'CYZ': ('Cauayan', 'Philippines'),
    'CZA': ('Chichen Itza', 'Mexico'),
    'CZB': ('Cruz Alta', 'Brazil'),
    'CZC': ('Copper Center', 'United States'),
    'CZD': ('Coro', 'Venezuela'),
    'CZE': ('Coro', 'Venezuela'),
    'CZF': ('Cape Romanzof', 'United States'),
    'CZG': ('Champagne', 'Canada'),
    'CZH': ('Corozal', 'Belize'),
    'CZI': ('Changzhou', 'China'),
    'CZJ': ('Corazon de Jesus', 'Panama'),
    'CZK': ('Cascade Locks', 'United States'),
    'CZL': ('Constantine', 'Algeria'),
    'CZM': ('Cozumel', 'Mexico'),
    'CZN': ('Chisana', 'United States'),
    'CZO': ('Chistochina', 'United States'),
    'CZP': ('Cape Pole', 'United States'),
    'CZQ': ('Coquimbo', 'Chile'),
    'CZR': ('Cozumel', 'Mexico'),
    'CZS': ('Cruzeiro do Sul', 'Brazil'),
    'CZT': ('Carrizo Springs', 'United States'),
    'CZU': ('Corozal', 'Colombia'),
    'CZV': ('Cozumel', 'Mexico'),
    'CZW': ('Czestochowa', 'Poland'),
    'CZX': ('Changzhou', 'China'),
    'CZY': ('Cluny', 'Australia'),
    'CZZ': ('Campo', 'Brazil'),
}

def get_airport_info(code):
    """
    Get city and country information for an airport code
    
    Args:
        code (str): IATA airport code
        
    Returns:
        dict: Dictionary with 'city' and 'country' keys, or None if not found
    """
    code = code.upper().strip()
    
    if code in AIRPORT_DATABASE:
        city, country = AIRPORT_DATABASE[code]
        return {
            'code': code,
            'city': city,
            'country': country
        }
    else:
        # Return unknown if not found
        return {
            'code': code,
            'city': 'Unknown',
            'country': 'Unknown'
        }

def get_airport_display_name(code):
    """
    Get a formatted display name for an airport code
    
    Args:
        code (str): IATA airport code
        
    Returns:
        str: Formatted string like "ACC - Accra, Ghana" or "XXX - Unknown"
    """
    info = get_airport_info(code)
    if info['city'] == 'Unknown':
        return f"{code} - Unknown"
    else:
        return f"{code} - {info['city']}, {info['country']}"

